/* 국뽕 뉴스 데이터 — 자동 수집기가 이 파일만 수정한다.
   갱신일: 2026-10-02
   index.html 의 CSS/함수는 절대 건드리지 말 것. */
const NEWS = [
  {cat:"tech", date:"2026-10-01", econ:true, intl:true, country:"글로벌", size:"대기업", company:"한국 반도체 산업(삼성전자·SK하이닉스 등)", wclass:"세계1위", world:"전 세계가 AI 데이터센터를 짓는 데 쓴 돈의 상당분이 한 달 만에 603억 달러어치 한국 반도체 청구서로 돌아왔다 — AI 인프라 확장의 물리적 병목을 한국이 쥐고 있다는 뜻이다.", pride:true,
   title:"한 달에 반도체만 603억 달러…세계 AI 투자 청구서가 한국으로 왔다",
   desc:"산업통상자원부 집계에서 2026년 9월 수출액이 1209억 4000만 달러로 월간 기준 역대 최대를 기록했다. 월 수출이 1200억 달러를 넘은 것은 처음이다. 주역은 반도체로, 9월 반도체 수출은 603억 달러를 기록해 사상 처음 월 600억 달러를 돌파했다. 에이전틱 AI 확산과 글로벌 AI 인프라 투자가 겹치며 컴퓨터 수출도 70억 달러로 월 기준 역대 최대를 찍었다. 1~9월 누적 수출은 8145억 달러로 처음 8000억 달러를 넘어서, 연간 1조 달러 수출국 진입이 사정권에 들어왔다.",
   src:"서울신문", url:"https://www.seoul.co.kr/news/economy/2026/10/02/20261002031001",
   yt:5, ytnote:"AI 데이터센터 한 동을 지을 때마다 한국에 얼마가 꽂히나 — 월 603억 달러 반도체 수출의 해부도",
   videos:[{t:"지난달 수출, 역대 9월 중 1위...반도체, 사상 최대 / YTN", u:"https://www.youtube.com/watch?v=deMPD-fLets"},
            {t:"9월 수출 역대 최대…반도체·자동차 '쌍끌이' / 연합뉴스TV", u:"https://www.youtube.com/watch?v=-RitNGCTido"},
            {t:"\"한국이 세계 무역을 뒤흔들고 있다\" 외신이 주목한 역대급 수출 기록", u:"https://www.youtube.com/watch?v=0dHAuoHYubM"}],
   related:[{t:"韓 수출 8000억달러 첫 돌파…9월 1209억 최대, '반도체'가 절반 (글로벌이코노믹)", u:"https://www.g-enews.com/article/Industry/2026/10/20261001113920239727fa31d75c_1"},
            {t:"반도체 첫 600억 달러 돌파…9월 수출 역대 최대 1209억 달러 (한국일보)", u:"https://www.hankookilbo.com/news/article/A2026100109120004688"}]},

  {cat:"tech", date:"2026-09-30", econ:true, intl:true, country:"글로벌", size:"대기업", company:"HD한국조선해양·삼성중공업·한화오션", wclass:"글로벌수주", world:"LNG운반선·FLNG 같은 고부가 선종에서 세계 선주들이 한국 빅3 외에 갈 곳을 찾지 못해, 9월까지 256척·383억 달러가 몰리며 연간 목표를 초과 달성했다.", pride:true,
   title:"세계 선주들이 줄 섰다…K-조선 빅3, 9월까지 383억 달러 수주",
   desc:"HD한국조선해양·삼성중공업·한화오션의 2026년 9월 30일 기준 누적 수주가 256척·383억 2000만 달러로 집계됐다. HD한국조선해양이 169척·187억 1000만 달러로 연간 목표의 80.3%를, 삼성중공업은 상선 44척·75억 달러로 목표 57억 달러를 초과한 132.0%를 달성했고 한화오션은 77억 1000만 달러를 쌓았다. LNG운반선·FLNG·VLEC 등 중국이 아직 품질과 납기를 맞추지 못하는 고부가 선종에 수주가 집중됐다. 한화오션은 9월 대만 양밍해운에서만 컨테이너선 6척 1조 5527억원을 따냈다.",
   src:"더빅데이터", url:"https://www.thebigdata.co.kr/view.php?ud=202610010949271770570d99e4c8_23",
   yt:4, ytnote:"중국이 척수로 이기는데 왜 돈은 한국이 버나 — 고부가 선종 점유율로 본 조선 빅3의 해자",
   videos:[{t:"조선 '빅3', 카타르 LNG선 수주 마무리...한화오션 '잭팟' 낭보!", u:"https://www.youtube.com/watch?v=weikmz2xXc8"},
            {t:"[여의도튜브] 1척당 100억씩...\"LNG선 밀물이 들어온다\" / 머니투데이방송", u:"https://www.youtube.com/watch?v=SoOcjGsGn4w"},
            {t:"절박한 日 조선업, K조선에 LNG선 기술협력 요청..?", u:"https://www.youtube.com/shorts/s9C3fEEjXis"}],
   related:[{t:"조선 3사, 수주 400억달러 눈앞…목표 넘고 지난해 실적도 추월 (글로벌이코노믹)", u:"https://www.g-enews.com/article/Industry/2026/09/2026093015010154524debea800_1"},
            {t:"한화오션, 양밍해운서 1조 5527억원 규모 컨선 6척 수주 (뉴스1)", u:"https://www.news1.kr/industry/general-industry/6278291"}]},

  {cat:"tech", date:"2026-08-05", econ:true, intl:true, country:"미국·유럽", size:"중견", company:"알테오젠", wclass:"대체불가", world:"정맥주사를 피하주사로 바꾸는 히알루로니다제 플랫폼을 세계에서 사실상 두 곳만 보유하고, 세계 매출 1위 항암제 키트루다의 피하주사 버전이 이 한국 기술 위에서 FDA 허가를 받아 분기 4억 6300만 달러를 팔았다.", pride:true,
   title:"세계 1위 항암제가 한국 기술 위에 올라탔다…알테오젠, 올해만 1.8조 기술수출",
   desc:"알테오젠이 2026년 8월 5일 5219억원 규모 신규 기술수출 계약을 공시하며 올해 누적 기술수출이 1조 8000억원대로 불었다. 핵심은 정맥주사(IV) 제형을 피하주사(SC)로 바꾸는 인간 히알루로니다제 플랫폼 'ALT-B4'로, 상용화 수준에서 이 기술을 가진 곳은 미국 할로자임과 알테오젠뿐이다. ALT-B4가 적용된 MSD의 '키트루다 큐렉스'는 FDA 허가를 받아 2026년 2분기에만 4억 6300만 달러가 팔렸고, 알테오젠은 매출 로열티로 연간 조 단위 수취가 전망된다. 글로벌 빅파마가 자사 블록버스터의 수명을 늘리려면 한국 중견 바이오텍과 계약하는 수밖에 없는 구조다.",
   src:"아시아경제", url:"https://view.asiae.co.kr/article/2026080508174110115",
   yt:4, ytnote:"주사 한 방을 정맥에서 피하로 바꾸면 특허가 10년 늘어난다 — 알테오젠이 쥔 제형 전환의 경제학",
   videos:[{t:"알테오젠 완전분석｜MSD·노바티스·GSK·바이오젠이 ALT-B4를 선택한 이유", u:"https://www.youtube.com/watch?v=__Bw0Ep0FOI"},
            {t:"알테오젠, 미 FDA 뚫었다…\"연간 로열티만 1조\" / 한국경제TV뉴스", u:"https://www.youtube.com/watch?v=ujKTB0eLr5E"},
            {t:"알테오젠 코스피 이전과 ALT-B4 기술 해자 집중 분석", u:"https://www.youtube.com/watch?v=PPrL_ZpxFU4"}],
   related:[{t:"알테오젠, 올해만 1.8조 기술수출…특허·계약·상업화 '삼박자' (이투데이)", u:"https://www.etoday.co.kr/news/view/2611182"},
            {t:"알테오젠, SC제형 유럽특허 확보…한미·오스코텍은 조단위 기술수출 성사 (서울경제)", u:"https://www.sedaily.com/article/20054151"}]},

  {cat:"tech", date:"2026-02-12", econ:true, intl:true, country:"미국", size:"대기업", company:"삼성전자", wclass:"세계최초", world:"6세대 고대역폭메모리 HBM4를 세계에서 가장 먼저 양산·출하했고, 그 첫 물량을 엔비디아가 가져갔다 — AI 가속기의 다음 세대 성능 상한을 한국 메모리가 먼저 열었다.", pride:true,
   title:"HBM4 깃발을 세계에서 먼저 꽂았다…첫 양산 물량은 엔비디아행",
   desc:"삼성전자가 6세대 고대역폭메모리 HBM4를 세계 최초로 양산·출하했다고 2026년 2월 밝혔다. 엔비디아향 HBM4 샘플 품질 테스트를 가장 먼저 통과한 데 이어 양산·출하까지 당초 일정보다 약 일주일 앞당겼다. 국제산업표준기구(JEDEC) 기준을 웃도는 성능 목표를 개발 착수 단계부터 잡았고, 최선단 1c D램과 4나노 베이스 다이를 적용해 재설계 없이 양산 초기부터 안정적 수율과 업계 최고 성능을 확보했다. HBM4는 엔비디아 차세대 GPU의 성능을 좌우하는 부품으로, 누가 먼저 양산하느냐가 곧 다음 2년의 AI 메모리 판도를 정한다.",
   src:"머니투데이", url:"https://www.mt.co.kr/industry/2026/02/12/2026021215150041209",
   yt:5, ytnote:"1c D램과 4나노 베이스 다이 — 삼성이 HBM4에서 '재설계 없이' 수율을 잡은 설계 선택 해부",
   videos:[{t:"삼성전자, 세계 최초 HBM4 양산 출하…\"업계 최고 성능\" / YTN 사이언스", u:"https://www.youtube.com/watch?v=2QtsNRhllbA"},
            {t:"삼성전자, HBM4 세계 최초 양산·출하…차세대 AI 메모리 '선공' / 머니투데이방송", u:"https://www.youtube.com/watch?v=m73O4Dh3n3g"},
            {t:"삼성전자, 엔비디아 최신 GPU용 HBM4 세계 첫 양산 스타트!", u:"https://www.youtube.com/watch?v=upnoCjwYArM"}],
   related:[{t:"삼성, HBM4 깃발 먼저 꽂았다…'세계 최초' 엔비디아에 양산 출하 (아시아경제)", u:"https://view.asiae.co.kr/article/2026021216022672651"},
            {t:"삼성전자, HBM4 세계 첫 양산…엔비디아 공급 뚫었다 (다음뉴스)", u:"https://v.daum.net/v/20260212162019401"}]},

  {cat:"tech", date:"2026-06-04", econ:true, intl:true, country:"대만·미국", size:"중소", company:"파두(FADU)", wclass:"글로벌수주", world:"글로벌 빅테크가 이미 채택해 운용 중인 Gen5 SSD 컨트롤러에 이어, 대만에서만 604억원 규모 기업용 SSD 공급계약을 따내며 누적 신규 수주 3000억원을 넘겼다 — 삼성·마벨이 과점하던 데이터센터 SSD 컨트롤러 시장에 한국 중소 팹리스가 실제 매출로 진입했다.", pride:true,
   title:"삼성·마벨이 나눠 먹던 시장…한국 팹리스가 수주 3000억을 넘겼다",
   desc:"데이터센터 반도체 팹리스 파두가 대만 '컴퓨텍스 2026'에서 차세대 Gen6 SSD 컨트롤러를 처음 공개하고 아시아 데이터센터·서버 시장 공략에 나섰다. 올해 대만 시장에서만 604억원 규모 기업용 SSD 완제품 공급계약을 따냈고, 6월 초 기준 공시 누적 신규 수주액이 3000억원을 넘어섰다. Gen6는 이전 세대 대비 성능과 전력효율이 두 배 이상 개선됐고, AI 추론용 스토리지에서 중요한 대용량 블록 랜덤 읽기·쓰기 성능이 업계 최고 수준이다. 글로벌 빅테크가 이미 파두의 Gen5 컨트롤러를 채택해 운용 중이다.",
   src:"디지털데일리", url:"https://www.ddaily.co.kr/page/view/2026060415373207347",
   yt:4, ytnote:"SSD의 두뇌를 누가 만드나 — 국내 팹리스가 데이터센터 컨트롤러 시장을 뚫은 경로 추적",
   videos:[{t:"파두ㅣ삼성전자 수준의 SSD 컨트롤러 기술력 보유ㅣ공시진단ㅣ한국경제TV", u:"https://www.youtube.com/watch?v=6fD3liWy3g0"},
            {t:"[기업분석] 파두, SSD 시장 글로벌 도약 기대", u:"https://www.youtube.com/watch?v=SSLWZKrb2_8"},
            {t:"파두, 신규 고객사 확보 '자신감' [기업INSIDE] / 머니투데이방송", u:"https://www.youtube.com/watch?v=gz8BMnmImnQ"}],
   related:[{t:"파두, 컴퓨텍스서 Gen6 SSD 공개…대만 수주 3000억 돌파 (아이뉴스24)", u:"https://inews24.com/view/1973746"},
            {t:"[컴퓨텍스2026] 파두, Gen6 SSD 컨트롤러로 글로벌 시장 공략 (블로터)", u:"https://www.bloter.net/news/articleView.html?idxno=664373"}]},

  {cat:"sports", date:"2026-09-27", econ:false, intl:true, country:"일본", pride:true,
   title:"일본 안방에서 3-1…아시안게임 야구 5연패, 하계 AG 통산 800번째 금메달",
   desc:"한국 야구대표팀이 2026년 9월 27일 일본 아이치현 도요하시 시민구장에서 열린 아이치·나고야 아시안게임 결승에서 일본을 3-1로 꺾고 대회 5회 연속 우승을 차지했다. 선발 곽빈이 일본 타선을 묶었고 김도영이 결승타를 쳤다. 이 금메달은 한국의 하계 아시안게임 통산 800번째 금메달과 맞물린 상징적인 승리로, 개최국 안방에서 일본을 잡고 만든 기록이라는 점에서 의미가 컸다.",
   src:"Olympics.com", url:"https://www.olympics.com/ko/news/baseball-korea-japan-final-asian-games-aichi-nagoya-2026",
   yt:4, ytnote:"개최국 안방에서 5연패 — 곽빈의 투구 배합과 김도영의 결승타를 다시 본다",
   videos:[{t:"[2026 아시안게임] 야구 결승전 대한민국 vs 일본 | 한국 AG 5연패!", u:"https://www.youtube.com/watch?v=B_wdRn5be-8"},
            {t:"[2026아시안게임] 곽빈이 막았고 김도영이 때렸다 ⚾ 야구 결승 대한민국 vs 일본", u:"https://www.youtube.com/watch?v=6jq_wSnrHOM"},
            {t:"[정민철·오승환의 말말말] 일본에 설욕하고 5회 연속 금메달 | 2026 아시안게임", u:"https://www.youtube.com/watch?v=u-KYbR7s3EU"}],
   related:[{t:"나고야 아시안게임 개막…한국 800호 금메달까지 13개 (매일신문)", u:"https://www.imaeil.com/page/view/2026091908352894222"},
            {t:"아시안게임: 한국 선수단 전 종목 메달리스트 모아보기 (Olympics.com)", u:"https://www.olympics.com/ko/news/korea-complete-list-winners-medallists-asian-games-2026"}]},

  {cat:"tech", date:"2026-09-22", econ:true, intl:true, country:"글로벌", size:"중견", company:"한미반도체", wclass:"세계최초", world:"기존 20mm급이 한계였던 인터포저를 75mm×75mm까지 키운 대면적 2.5D 플립칩 본딩 장비를 세계 최초로 양산 출하해, AI 가속기 패키징 장비를 사실상 한국 중견기업이 먼저 상용화했다.", pride:true,
   title:"AI 가속기 패키징의 다음 장비, 세계 최초 출하는 한국 중견기업이었다",
   desc:"한미반도체가 AI 시스템반도체용 대면적 2.5D 패키징 장비 'FC 본더 75'를 글로벌 고객사에 첫 출하했다. 75mm×75mm 크기의 대형 인터포저 패키징을 지원해, 범용 패키징 크기인 20mm×20mm의 벽을 열 배 이상 넓혔다. CPU·GPU·HBM을 한 패키지에 묶는 2.5D 수요가 파운드리·OSAT로 번지면서 고스펙 장비를 먼저 낸 쪽이 표준을 쥐는 구조다. 한미반도체는 올해 FC 본더 3.5, 2.5D TC 본더 40 C2S·C2W를 잇따라 내놓고 '2.5D TC 본더 120' 출시를 앞뒀으며, 10월 미국 법인 '한미USA' 설립도 예정했다.",
   src:"ZDNet Korea", url:"https://zdnet.co.kr/view/?no=20260922153758",
   yt:4, ytnote:"HBM 본더로 세계를 먹은 회사가 왜 인터포저를 75mm로 키웠나 — 2.5D 패키징 장비 전쟁 해설",
   videos:[{t:"한미반도체, 국내 1등 어드밴스드 패키징 장비 업체로 맹활약", u:"https://www.youtube.com/watch?v=rc-28FQJxvU"},
            {t:"한미반도체 최대 실적! 기술 난제 뚫어버린 '와이드 TC본더'", u:"https://www.youtube.com/watch?v=Tc5UljM9l08"},
            {t:"한미반도체, 어드밴스드 패키징 관련 TSV 본딩 장비", u:"https://www.youtube.com/watch?v=e8zWORHnZjQ"}],
   related:[{t:"한미반도체, AI 시스템반도체용 'FC 본더 75' 첫 출하 (헤럴드경제)", u:"https://biz.heraldcorp.com/article/10882235"},
            {t:"한미반도체, HBM 넘어 AI 패키징으로…'FC 본더 75' 첫 출하 (글로벌이코노믹)", u:"https://www.g-enews.com/article/Industry/2026/09/202609220913392793084322ec9_1"}]},

  {cat:"tech", date:"2026-09-25", econ:true, intl:true, country:"글로벌", size:"대기업", company:"SK하이닉스", wclass:"세계1위", world:"AI 시대의 병목인 HBM에서 세계 점유율 50%를 쥐고 74조원 시장의 1위를 지키고 있다 — 엔비디아 가속기에 들어갈 메모리를 한국 두 회사가 합쳐 80% 이상 공급하는 구조다.", pride:true,
   title:"엔비디아가 사갈 HBM의 절반은 이 회사 것…74조 시장 1위를 지켰다",
   desc:"카운터포인트리서치 집계에서 SK하이닉스는 2026년 2분기 글로벌 HBM 시장 점유율 50%로 1위를 유지했다. 삼성전자가 33%까지 올라 추격했지만, 한국 두 회사의 합계 점유율은 80%를 넘는다. 올해 HBM 시장 규모는 74조원대로 커졌고, 엔비디아 AI 가속기의 성능 상한을 HBM 공급이 결정하는 구조가 굳어졌다. 미국 빅테크가 AI 투자를 늘릴 때마다 청구서의 상당 부분이 한국 메모리로 흘러가는 셈이다.",
   src:"글로벌이코노믹", url:"https://www.g-enews.com/article/Global-Biz/2026/09/202609251658393730fbbec65dfb_1",
   yt:4, ytnote:"AI 반도체의 진짜 병목은 연산이 아니라 메모리 — 점유율 50%가 뜻하는 협상력의 크기",
   videos:[{t:"[SK하이닉스] HBM 점유율+연간 영업이익, 어디까지 가나", u:"https://www.youtube.com/watch?v=b_FnBhNoR1k"},
            {t:"삼성전자, HBM4 '수율 80%' 돌파…SK하이닉스와 양산 전쟁 붙었다", u:"https://www.youtube.com/watch?v=NUapzCTVVwI"},
            {t:"2026년 HBM4 패권 경쟁, 삼성 생산능력 확대 vs SK하이닉스 M15X 팹 조기 가동", u:"https://www.youtube.com/watch?v=BHpTf4bqNk0"}],
   related:[{t:"Global HBM Market Share Q2 2026 (Counterpoint Research)", u:"https://counterpointresearch.com/ko/insights/global-hbm-market-share-q2-2026"},
            {t:"삼성전자, 내년 HBM 점유율 SK하이닉스 추월 전망", u:"https://www.youtube.com/watch?v=SZZzkDr7ZgY"}]},

  {cat:"tech", date:"2026-08-18", econ:true, intl:true, country:"글로벌", size:"중견", company:"HPSP", wclass:"대체불가", world:"선단 공정에서 계면 결함을 치유하는 고압 수소 어닐링 장비를 세계 고압 인증까지 갖춘 채 사실상 단독 공급해 왔다 — 글로벌 파운드리·메모리가 이 공정을 하려면 한국 중견기업 장비를 들여놓는 수밖에 없었다.", pride:true,
   title:"세계 파운드리가 줄 서서 사는 장비, 만드는 곳은 한국의 중견기업 하나였다",
   desc:"HPSP는 시스템LSI 파운드리와 선단 메모리 전공정에서 계면 결함을 치유하는 고압 수소 어닐링(HPA) 장비 분야에서 세계 고압 인증을 보유한 유일 업체로, 주요 고객사 팹에서 가동되는 HPA 장비가 사실상 이 회사 'GENI-SYS'뿐이었다. 미세화로 열적 마진이 줄면서 저온·고압 공정 수요가 커져 파운드리에서 D램·낸드로 적용이 확대되고 있다. 증권가는 2026년 매출 2341억 원, 영업이익 1245억 원으로 30%대 성장을 전망한다.",
   src:"머니투데이", url:"https://www.mt.co.kr/stock/2026/08/18/2026081818567086457",
   yt:4, ytnote:"영업이익률 50%가 나오는 장비 회사 — '세계 유일' 프리미엄이 붙는 소부장의 조건",
   videos:[{t:"HPSP 독점 공급 장비에 도전한 예스티 \"알파테스트 완료\"", u:"https://www.youtube.com/watch?v=Dq2wBRTEmjY"},
            {t:"[HPSP 주가 전망] 예스티 변수, 급등락 폭탄까지! 고압수소어닐링 독점 \"끝난걸까?\"", u:"https://www.youtube.com/watch?v=RCcGA5L3gB8"}],
   related:[{t:"[IR일문일답] HPSP, 고압어닐링 경쟁자가 없다…미세 반도체 시장 주도 (더인베스트)", u:"https://www.theinvest.co.kr/article/645"},
            {t:"세계 유일 독점 기업 HPSP, 성장 정체의 역설에 빠지다 (리드경제)", u:"https://www.leadeconomy.co.kr/news/articleView.html?idxno=7100"}]},

  {cat:"tech", date:"2026-08-14", econ:true, intl:true, country:"미국·중국·유럽·일본·대만", size:"스타트업", company:"딥엑스(DEEPX)", wclass:"해외인정", world:"GPU 대비 전력효율 20배를 내세운 국산 NPU가 양산 1년 만에 9개국에서 공급계약 77건, 누적 1300만 달러를 따내며 현대차·바이두까지 고객으로 확보했다 — 엣지 AI 칩을 해외 기업들이 한국 스타트업에서 사가고 있다.", pride:true,
   title:"양산 1년, 9개국 77건…한국 스타트업 AI 칩을 세계가 사갔다",
   desc:"온디바이스 AI 반도체 팹리스 딥엑스가 NPU 'DX-M1' 양산 1년 만에 미국·중국·유럽·대만·일본 등 9개 주요 국가에서 공급계약 77건, 누적 1300만 달러 규모를 확보했다. 양산 개시 후 첫 5개월 주문은 2건이었지만 올해 들어 석 달도 안 돼 25건이 추가되는 식으로 기울기가 꺾였고, 전 세계 350개 PoC가 밑거름이 됐다. 로보틱스·스마트팩토리·AI 엣지서버·산업용 AI·지능형 영상보안·스마트시티 등 피지컬 AI 7개 분야에 들어가며, 현대차와 바이두를 고객으로 확보했다. 애플·시스코 출신 김녹원 대표가 2018년 세운 회사다.",
   src:"아시아경제", url:"https://view.asiae.co.kr/article/2026081410572995280",
   yt:5, ytnote:"GPU 300W를 5W로 대체한다는 주장의 진위 — 국산 NPU가 엣지에서 엔비디아를 피해 이긴 방법",
   videos:[{t:"'데이터센터 없는 AI가 온다' 300W급 성능 5W로 구현하는 온디바이스 AI", u:"https://www.youtube.com/watch?v=X47yAfRMqdg"},
            {t:"대통령도 깜짝 놀란 K-반도체 비밀병기, 딥엑스의 '괴물 NPU'", u:"https://www.youtube.com/watch?v=TTpZ4aZVCAk"},
            {t:"온디바이스 AI반도체 전문기업, DEEPX (딥엑스)", u:"https://www.youtube.com/watch?v=XFYNKXhkndc"}],
   related:[{t:"딥엑스, 양산 7개월 만에 8개국서 27건 수주 (이데일리)", u:"https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=03539126645388568"},
            {t:"딥엑스, 현대차·바이두 고객 확보…차세대 AI칩 내년 양산", u:"https://m.news.nate.com/view/20260414n26035"}]},

  {cat:"tech", date:"2026-07-19", econ:true, intl:true, country:"글로벌", size:"스타트업", company:"디노티시아", wclass:"세계최초", world:"벡터 데이터 검색·처리만 전담하는 전용 반도체 VDPU를 세계 최초로 설계해 테이프아웃까지 끝냈다 — GPU 중심 AI 인프라에서 아무도 손대지 않은 계층을 한국 스타트업이 먼저 칩으로 만들었다.", pride:true,
   title:"GPU가 못 보던 자리를 칩으로 만들었다…세계 최초 '벡터 전용 반도체'",
   desc:"디노티시아가 세계 최초로 개발한 VDPU(Vector Data Processing Unit)의 성능평가를 진행하며 벡터 DB '씨홀스'와 묶어 AI 데이터 인프라 기업으로 전환을 선언했다. VDPU는 생성형 AI 환경에서 폭증하는 벡터 데이터의 검색·처리 계층만 가속하는 전용 칩으로, GPU 중심 구조가 비워둔 병목을 정면으로 노린다. 씨홀스는 GS인증 1등급과 클라우드 SaaS 정식판을 확보했고, VDPU는 테이프아웃을 마쳐 하반기 제품 공개·양산을 목표로 한다. 올해 4월 유치한 시리즈A 900억원은 파네시아(800억)·리벨리온(620억)·사피온(600억)을 넘는 국내 AI 반도체 스타트업 역대 최대 시리즈A다.",
   src:"전자신문", url:"https://www.etnews.com/20260719000060",
   yt:3, ytnote:"RAG 시대의 진짜 병목은 검색이다 — 벡터 DB를 칩으로 내려버린 설계 아이디어",
   videos:[],
   related:[{t:"디노티시아, 시리즈A 900억원 유치…국내 AI 칩 최고 투자액 경신 (ZDNet)", u:"https://zdnet.co.kr/view/?no=20260421140808"},
            {t:"똘똘한 AI 만드는 '벡터DB'…반도체까지 직접 설계한 스타트업 (머니투데이)", u:"https://www.mt.co.kr/future/2026/02/27/2026022423451431728"}]},

  {cat:"kpop", date:"2026-09-15", econ:false, intl:true, country:"미국", pride:true,
   title:"BTS 기록을 넘었다…제니 '드라큘라', 빌보드 핫100 톱10 16주",
   desc:"제니와 호주 밴드 테임 임팔라의 협업곡 '드라큘라'가 빌보드 메인 싱글 차트 '핫 100'에서 통산 16주째 톱10에 머물렀다. 2021년 방탄소년단 'Butter'가 세운 15주 기록을 넘어, K팝 그룹·솔로를 통틀어 핫 100 톱10에 가장 오래 머문 기록이 됐다. 최고 순위는 5위. 한국 가수의 해외 히트가 '반짝 1위'가 아니라 미국 라디오·스트리밍에 오래 얹히는 체류형 히트로 바뀌고 있음을 보여주는 수치다.",
   src:"서울신문", url:"https://www.seoul.co.kr/news/life/pop-culture/2026/09/15/20260915500197",
   yt:4, ytnote:"1위 한 번보다 어려운 '16주 톱10' — 미국 라디오 차트가 K팝을 받아들이는 방식 해설",
   videos:[{t:"제니·테임 임팔라 '드라큘라' 빌보드 핫100 10위 올랐다 / SBS 굿모닝연예", u:"https://www.youtube.com/watch?v=eNO1DYxKPZI"},
            {t:"제니, 빌보드 라디오 차트 1위..'골든' 이어 두 번째 / SBS 모닝와이드", u:"https://www.youtube.com/watch?v=tzdLUm_6RNo"},
            {t:"제니 드라큘라 빌보드 진입 인터뷰", u:"https://www.youtube.com/shorts/-bHjVIBbOtM"}],
   related:[{t:"Billboard Korea 차트", u:"https://www.billboard.co.kr/charts/billboard-korea-global-k-songs/"},
            {t:"올데프·NCT위시·엔플라잉까지…연휴 끝나고 K팝 시장 열린다 (뉴스핌)", u:"https://www.newspim.com/news/view/20260928000749"}]},

  {cat:"sports", date:"2002-06-22", classic:true, econ:false, intl:false, pride:true, title:"2002 한일월드컵, 스페인 꺾고 아시아 최초 4강…'4강 신화'가 시작된 날",
   desc:"2002년 6월 22일 광주에서 열린 한일월드컵 8강전에서 한국이 스페인과 120분 혈투 끝에 승부차기 5-3으로 승리하며 아시아 국가 최초로 월드컵 4강에 올랐다. 이운재의 선방과 홍명보의 마지막 킥이 역사를 만들었고, 전국 거리에는 수백만 명의 붉은 물결이 쏟아졌다. 1954년 첫 출전 이후 48년 만에 본선 첫 승(폴란드전)을 거둔 대회이기도 하다.",
   src:"Wikipedia", url:"https://en.wikipedia.org/wiki/2002_FIFA_World_Cup",
   yt:5, ytnote:"승부차기 5-3, 그날의 120분을 다시 본다 — 4강 신화 완전 복기",
   videos:[{t:"'4강 신화', 호아킨 막은 이운재와 마무리한 홍명보 | 2002 FIFA 월드컵 8강 대한민국 VS 스페인", u:"https://www.youtube.com/watch?v=6Kr-_veieNw"},
           {t:"[리플레이] 대한민국이 아시아 최초로 월드컵 4강에 진출했던 순간", u:"https://www.youtube.com/watch?v=ibnH3f2UIY8"},
           {t:"\"4강 신화 탄생! 스페인을 승부차기에서 꺾습니다!\" 2002년 한일 월드컵 스페인전 / SBS", u:"https://www.youtube.com/watch?v=I9Owon_gk5E"}],
   related:[{t:"2002 한일월드컵 4강 신화 태극전사 재조명 (한국생활체육뉴스)", u:"http://www.kstnews.co.kr/news/articleView.html?idxno=21138"},
            {t:"[다시보는 2002 월드컵] 한국축구 4강 신화 하이라이트", u:"https://www.youtube.com/watch?v=kdYsF6rbMjs"}]},

  {cat:"culture", date:"2020-02-09", classic:true, econ:false, intl:true, country:"미국", pride:true, title:"'기생충', 아카데미 작품상 수상…92년 역사상 비영어 영화 최초",
   desc:"봉준호 감독의 '기생충'이 2020년 2월 9일(현지시각) 제92회 아카데미 시상식에서 작품상·감독상·각본상·국제장편영화상 4관왕에 올랐다. 비영어권 영화가 아카데미 작품상을 받은 것은 시상식이 시작된 이래 처음이며, 비영어 영화가 작품상과 감독상을 동시에 가져간 것도 사상 최초다. \"1인치 자막의 장벽을 넘으면\"이라는 봉 감독의 수상 소감은 그해 전 세계가 인용한 문장이 됐다.",
   src:"VOA 코리아", url:"https://www.voakorea.com/a/korea_korea-life_academyawards-parasite/6029036.html",
   yt:5, ytnote:"1인치 자막의 장벽 — '기생충'이 오스카 92년의 규칙을 깬 과정 복기",
   videos:[{t:"아카데미 작품상 '기생충' 호명되는 순간… / YTN", u:"https://www.youtube.com/watch?v=zGms9ShsjjA"},
           {t:"[제92회 아카데미] \"92년 오스카 벽 부쉈다!\"…'기생충' 작품상 수상 외신 반응은? / KBS", u:"https://www.youtube.com/watch?v=5tV-B8zJ6Y8"},
           {t:"'기생충' 작품상까지 4관왕…아카데미 92년 역사 깼다 | 뉴스A", u:"https://www.youtube.com/watch?v=aZKljkRE38w"}],
   related:[{t:"<기생충> 제92회 아카데미 시상식 4관왕, 2020 아카데미 최다 수상 (CJ 뉴스룸)", u:"https://cjnews.cj.net/%EA%B8%B0%EC%83%9D%EC%B6%A9-%EC%A0%9C92%ED%9A%8C-%EC%95%84%EC%B9%B4%EB%8D%B0%EB%AF%B8-%EC%8B%9C%EC%83%81%EC%8B%9D-%EC%9E%91%ED%92%88%EC%83%81-%EA%B0%90%EB%8F%85%EC%83%81-%EA%B0%81%EB%B3%B8/"},
            {t:"美 연예 매체 \"기생충, 역대 최고의 오스카 작품상 수상작\" / YTN", u:"https://www.youtube.com/watch?v=9JflQ6MW0ZE"}]},

  {cat:"sports", date:"2010-02-26", classic:true, econ:false, intl:false, pride:true, title:"김연아, 밴쿠버 올림픽 피겨 금메달…총점 228.56 세계신기록으로 아시아 벽을 깼다",
   desc:"2010년 2월 26일 밴쿠버 동계올림픽 피겨스케이팅 여자 싱글에서 김연아가 프리 150.06점, 총점 228.56점이라는 세계 최고기록으로 금메달을 차지했다. 한국인 최초의 올림픽 피겨 금메달이자, 쇼트·프리·총점 세계기록을 한 대회에서 모두 갈아치운 기록이었다. 2위와의 점수 차는 23점이 넘었고, 거슈윈 피아노 협주곡에 맞춘 그 연기는 지금도 피겨 역사상 최고의 프로그램으로 꼽힌다.",
   src:"VOA 코리아", url:"https://www.voakorea.com/a/a-35-2010-02-26-voa6-91416569/1329877.html",
   yt:5, ytnote:"228.56 — 16년이 지나도 회자되는 4분간의 완벽, 점수표로 뜯어보기",
   videos:[{t:"\"김연아! 피겨 여왕의 시대가 열립니다!\" 2010 밴쿠버 김연아 금메달 연기 (풀영상) / SBS", u:"https://www.youtube.com/watch?v=2DEDNW5Jq4Q"},
           {t:"김연아, 환상적인 연기로 세계 신기록을 달성했던 역사적인 순간｜2010 밴쿠버 프리프로그램", u:"https://www.youtube.com/watch?v=SJqdiEHs-xE"},
           {t:"[올림픽 공식] 김연아가 말하는 2010 밴쿠버 동계올림픽 금메달의 순간", u:"https://www.youtube.com/watch?v=R8Z97TLObnk"}],
   related:[{t:"Kim Yu-na, Women's Singles Figure Skating | Vancouver 2010 (Olympics.com)", u:"https://www.olympics.com/en/video/kim-yu-na-women-s-singles-figure-skating-vancouver-2010"},
            {t:"[오마이뉴스 선정 21세기 100대 뉴스] 김연아 밴쿠버 여자 피겨 금메달", u:"https://www.ohmynews.com/NWS_Web/Event/20th/at_pg.aspx?CNTN_CD=A0002612674"}]},

  {cat:"culture", date:"2022-09-12", classic:true, econ:false, intl:true, country:"미국", pride:true, title:"'오징어 게임', 에미상 감독상·남우주연상 수상…74년 역사상 비영어 드라마 최초",
   desc:"2022년 9월 12일(현지시각) 제74회 프라임타임 에미상에서 넷플릭스 '오징어 게임'의 황동혁 감독이 드라마 시리즈 감독상을, 이정재가 남우주연상을 받았다. 비영어권 드라마가 에미상 감독상과 남우주연상을 수상한 것은 74년 역사상 처음이며, 작품상 후보에 오른 것도 비영어 드라마로는 최초였다. 이정재는 한국어로 수상 소감을 남기며 국내 시청자들과 기쁨을 나눴다.",
   src:"MBC 뉴스", url:"https://imnews.imbc.com/replay/2022/nw1200/article/6407256_35715.html",
   yt:5, ytnote:"자막의 벽을 두 번째로 무너뜨린 밤 — '오징어 게임'이 에미상에서 바꾼 규칙",
   videos:[{t:"'오징어 게임' 에미상서 이정재 남우주연상, 황동혁 감독상 수상 / KBS 2022.09.13.", u:"https://www.youtube.com/watch?v=CpRcvHlfWV8"},
           {t:"에미상 휩쓴 '오징어 게임'‥비영어권 최초 (2022.09.14/뉴스투데이/MBC)", u:"https://www.youtube.com/watch?v=6z-dPWLnLmI"},
           {t:"'오징어게임' 이정재·황동혁 센스 만점 수상 소감 (현장영상) / SBS", u:"https://www.youtube.com/watch?v=qSbCd_5LqYg"}],
   related:[{t:"'오징어게임', 비영어 드라마 최초 에미상 작품상 후보 (경향신문)", u:"https://www.khan.co.kr/article/202207130751001"},
            {t:"'오징어 게임' 미국 에미상 감독상·남우주연상 수상…비영어권 최초 / KBS", u:"https://www.youtube.com/watch?v=USsIy6EjGMQ"}]},

  // ── 국제기여 아카이브: 한국이 다른 나라를 도운 이야기 ──
  {cat:"culture", date:"1999-10-04", classic:true, aid:true, country:"동티모르", econ:false, intl:true, pride:true,
   title:"동티모르 상록수부대…구스마오 대통령이 취임 후 가장 먼저 찾은 나라가 한국이었다",
   desc:"1999년 10월 파병된 상록수부대는 동티모르 13개 군 가운데 로스팔로스와 오쿠시 2개 군에 각각 2년씩 주둔하며 4년간 지역 안정화를 이끌었다. 파견국 중 유일하게 대민지원 작전 '블루엔젤'을 별도로 전개해 동티모르 정부와 유엔군사령부로부터 '가장 모범적인 부대'라는 평가를 받았다. 임무 수행 중 순직한 부대원 5명의 추모식은 지금도 현지 오에쿠시에서 열린다.",
   legacy:"2002년 6월 취임한 구스마오 대통령은 외국 가운데 한국을 가장 먼저 방문해 파병에 사의를 표했고, 상록수부대가 주둔했던 지역 주민들을 \"동티모르인 가운데 가장 복 받은 주민\"이라고 표현했다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/policyNewsView.do?newsId=50002709",
   yt:5, ytnote:"한 나라의 대통령이 취임 후 첫 외국 방문지로 한국을 고른 이유 — 상록수부대 4년의 기록",
   videos:[{t:"[영상] 육군 상록수부대 동티모르 파병 (1999.10.04)", u:"https://www.youtube.com/watch?v=YQL3LyKkBZQ"},
           {t:"한국군 최초 PKO 상록수 부대 | 소말리아인이 놀란 상록수 부대", u:"https://www.youtube.com/watch?v=ZHQcd46Je_A"},
           {t:"동티모르 상록수부대 순직 15주기 추모식 열려 / YTN KOREAN", u:"https://www.youtube.com/watch?v=UCXMSncc8eA"}],
   related:[{t:"상록수부대(常綠樹部隊) — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0068134"},
            {t:"상록수부대 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%83%81%EB%A1%9D%EC%88%98%EB%B6%80%EB%8C%80"}]},

  {cat:"culture", date:"2007-07-19", classic:true, aid:true, country:"레바논", econ:false, intl:true, pride:true,
   title:"레바논 동명부대 18년…남부 티르 주민들이 부르는 이름은 '신이 준 선물'",
   desc:"2007년 6월 창설돼 7월 레바논 남부 티르 지역에 전개된 동명부대는 국군 해외파병 부대 가운데 최장수 부대다. UNIFIL 서부여단 소속으로 정전 감시와 폭발물 제거를 맡는 동시에, 의료지원과 학교·공공시설 개보수, 주민 일자리 창출형 민사작전을 이어왔다. 이스라엘-헤즈볼라 충돌이 반복되는 최전선에서 18년째 자리를 지키고 있다.",
   legacy:"현지 주민들은 동명부대를 '신이 준 선물'이라 부르며, 부대의 민군작전은 레바논 남부 안정화에 크게 기여한 것으로 평가받는다. 부대가 운영한 태권도 교실 출신 '레바논 태권도 키즈'는 지역의 상징이 됐다.",
   src:"한국민족문화대백과사전", url:"https://encykorea.aks.ac.kr/Article/E0080634",
   yt:4, ytnote:"18년을 한 도시에 머문 군대 — 티르 아이들이 한국어로 태권도 구령을 외치기까지",
   videos:[{t:"폭발물 제거, 의료 지원, 태권도 지도까지…레바논 티르의 동명부대 (KBS 2016.10.01)", u:"https://www.youtube.com/watch?v=r_-EVatiKPQ"},
           {t:"피쓰 투 레바논 — 국제평화를 지키는 그들의 이야기 #동명부대 #UNIFIL", u:"https://www.youtube.com/watch?v=7U01CCkV_T0"},
           {t:"레바논의 푸른 희망 동명부대 2부 [강군365 200회]", u:"https://www.youtube.com/watch?v=EXq55Sup3l4"}],
   related:[{t:"대한민국 레바논 평화 유지단 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EB%A0%88%EB%B0%94%EB%85%BC_%ED%8F%89%ED%99%94_%EC%9C%A0%EC%A7%80%EB%8B%A8"},
            {t:"내가 바로 레바논 태권도 키즈 #동명부대", u:"https://www.youtube.com/shorts/BuHdSrXD8TI"}]},

  {cat:"culture", date:"2013-04-01", classic:true, aid:true, country:"남수단", econ:false, intl:true, pride:true,
   title:"남수단 한빛부대, 307km '생명의 도로'…피보르 시장 \"남수단이 번영한 건 한빛부대 덕\"",
   desc:"2013년 남수단 종글레이주 보르에 전개된 한빛부대는 UNMISS 소속으로 12년 넘게 재건지원 임무를 이어오고 있다. 보르~피보르~아코보를 잇는 307km 주보급로를 보수해 현지 물류의 생명줄을 만들었고, 2014년에는 보르시에 르왈딧 초등학교를 세웠다. 한빛직업학교와 한빛농장으로 기술을 전수하고 한국어·태권도 교실도 운영한다.",
   legacy:"피보르 시장 보요이 골라는 \"남수단이 번영하고 무역이 활성화된 것은 한빛부대가 수백km 도로를 건설한 재건 작전 덕분\"이라 말했고, 구무룩 마을 위원장은 \"아이들과 여성, 노인 모두가 나아진 도로를 보고 행복해했다\"고 감사를 전했다. 현지에서 한빛부대의 별명은 '신이 내린 선물'이다.",
   src:"세계일보", url:"https://www.segye.com/newsView/20250330507167",
   yt:5, ytnote:"307km 흙길이 나라의 무역로가 되기까지 — 남수단이 한국군을 '신이 내린 선물'이라 부르는 이유",
   videos:[{t:"남수단 신이 내린 선물｜한빛부대 파병 10주년을 기하며", u:"https://www.youtube.com/watch?v=krCCOx5po3s"},
           {t:"[한빛부대 16진] 남수단 주민에 '생명의 도로' 선물", u:"https://www.youtube.com/watch?v=c0dgHNY7hxs"},
           {t:"\"신이 내린 선물\"…국군의 날 기념 해외파병부대(청해·아크·한빛·동명) 활약상 공개", u:"https://www.youtube.com/watch?v=y8IXVo2WMDQ"}],
   related:[{t:"남수단 국민은 왜 한빛부대를 \"신이 내린 선물\"이라 찬사 보낼까 (문화일보)", u:"https://news.nate.com/view/20250330n04489"},
            {t:"남수단 한빛부대 — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0080633"}]},

  {cat:"culture", date:"2010-03-08", classic:true, aid:true, country:"아이티", econ:false, intl:true, pride:true,
   title:"아이티 단비부대, 철수하며 110억원짜리 주둔지를 통째로 아이티에 넘겼다",
   desc:"2010년 1월 대지진 직후 창설된 단비부대는 3월 8일 레오간에 도착해 2년 9개월간 잔해 제거, 도로 복구, 하천 정비, 우물 개발을 수행했다. 공식 임무가 아니었는데도 난민들에게 우물을 파주고 마을과 학교를 지었으며, 콜레라 방역과 난민촌 진료를 병행했다. 2012년 12월 철수하면서 110억원 규모의 주둔지 시설물 전부를 아이티 정부에 무상 공여하고 떠났다.",
   legacy:"부대가 세운 초등학교와 우물, 그리고 통째로 남기고 간 주둔지 시설은 지금도 레오간에서 사용되고 있다 — 한국군이 '단비'라는 이름 그대로 기억되는 이유다.",
   src:"YTN", url:"https://m.ytn.co.kr/news_view.amp.php?param=0101_201212241602370439",
   yt:3, ytnote:"떠나면서 기지를 통째로 주고 온 부대 — 아이티 '단비'의 2년 9개월",
   videos:[],
   related:[{t:"대한민국 아이티 재건지원단 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EC%95%84%EC%9D%B4%ED%8B%B0_%EC%9E%AC%EA%B1%B4%EC%A7%80%EC%9B%90%EB%8B%A8"},
            {t:"아이티 단비부대, 즐겁고 훈훈한 태권도 현장", u:"https://www.youtube.com/watch?v=_HdWrVphUSM"}]},

  {cat:"culture", date:"2011-01-21", classic:true, aid:true, country:"미얀마·인도네시아", econ:false, intl:true, pride:true,
   title:"아덴만 여명작전…구출된 인질 21명 중 13명은 미얀마·인도네시아 선원이었다",
   desc:"2011년 1월 15일 소말리아 해적에 피랍된 삼호주얼리호를 구하기 위해 청해부대가 작전에 들어가, 피랍 6일 만인 1월 21일 해군특수전전단(UDT/SEAL)이 선박을 급습했다. 해적 8명을 사살하고 5명을 생포하며 인질 21명 전원을 무사히 구출했는데, 이 가운데 미얀마인 11명과 인도네시아인 2명 등 13명이 외국인 선원이었다. 미국·오만·파키스탄 등 다국적 함정이 작전을 지원했다.",
   legacy:"한국 해군이 자국민뿐 아니라 동남아 선원 13명의 목숨까지 함께 구해낸 이 작전은 해양 안보·인도주의 군사작전의 모범 사례로 국제 사회에서 거론된다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/policyNewsView.do?newsId=148726097",
   yt:5, ytnote:"구출된 21명 중 13명은 한국인이 아니었다 — 아덴만 여명작전을 다시 보는 관점",
   videos:[{t:"[국방부] 다큐멘터리 — 아덴만 여명작전 7일간의 기록", u:"https://www.youtube.com/watch?v=ywyBl1KaICw"},
           {t:"삼호주얼리호에 피랍된 21명의 선원들을 구하라! #벌거벗은세계사 EP.31 | tvN", u:"https://www.youtube.com/watch?v=AEjuA2zIPdY"},
           {t:"청해부대 아덴만 여명작전 영상 (S. Korean Navy Rescued Hostages from Somalia Pirates)", u:"https://www.youtube.com/watch?v=VrfvHWUCr_0"}],
   related:[{t:"아덴만 여명 작전 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%95%84%EB%8D%B4%EB%A7%8C_%EC%97%AC%EB%AA%85_%EC%9E%91%EC%A0%84"},
            {t:"소말리아 해역 청해부대 — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0080635"}]},

  {cat:"culture", date:"2023-02-08", classic:true, aid:true, country:"튀르키예", econ:false, intl:true, pride:true,
   title:"튀르키예 대지진, 한국 긴급구호대 118명…6·25 때 우리를 도운 그 땅에서 생존자를 꺼냈다",
   desc:"2023년 2월 6일 대지진 직후 외교부·국방부·소방청·KOICA로 구성된 해외긴급구호대(KDRT) 118명이 파견돼 2월 8일 오전 가지안테프 공항에 도착했다. 튀르키예 정부 요청에 따라 하타이주 안타키아를 중점 구조지역으로 선정했고, 2월 9일 구조 개시 90분 만에 첫 생존자를 구해낸 뒤 7시간 만에 5명을 구조했다. 구호대는 3진까지 이어져 3월까지 구조·재건 활동을 계속했다.",
   legacy:"튀르키예는 6·25 때 미국 다음으로 많은 병력을 보낸 '형제의 나라'이며, 한국 구호대가 활동한 지역은 당시 튀르키예군이 한국으로 떠났던 이스켄데룬 인근이었다 — 72년 만에 같은 항구에서 방향만 바뀐 셈이다.",
   src:"외교부", url:"https://www.mofa.go.kr/www/brd/m_4076/view.do?seq=369765",
   yt:5, ytnote:"72년 전 그 항구에서 — 형제의 나라에 진 빚을 갚으러 간 118명",
   videos:[{t:"한국 긴급 구호대, 튀르키예 지진 현장서 생존자 첫 구조", u:"https://www.youtube.com/watch?v=56RwgfnlCkk"},
           {t:"\"튀르키예, 형제의 나라\"…긴급구호대 110명 급파 | 뉴스A", u:"https://www.youtube.com/watch?v=uJOXF9bv4aE"},
           {t:"총 8명의 생존자를 구조하다! 튀르키예·시리아 대지진에서 활약한 대한민국 긴급구호대", u:"https://www.youtube.com/watch?v=KfVzVure7aM"}],
   related:[{t:"정부 긴급구호대 튀르키예 지진 현장 도착해 수색·구조활동 개시 (경향신문)", u:"https://m.khan.co.kr/politics/defense-diplomacy/article/202302081620001"},
            {t:"튀르키예 지진 피해 지원 대한민국 해외긴급구호대(KDRT) 3진 복귀 (외교부)", u:"https://www.mofa.go.kr/www/brd/m_4080/view.do?seq=373500"}]},

  {cat:"culture", date:"2013-12-09", classic:true, aid:true, country:"필리핀", econ:false, intl:true, pride:true,
   title:"태풍 하이옌 폐허의 필리핀에 520명 아라우부대…아키노 대통령이 한국말로 \"감사합니다\"",
   desc:"2013년 11월 슈퍼태풍 하이옌으로 초토화된 필리핀 타클로반에 12월 9일부터 520여 명 규모의 아라우부대가 전개됐다. 전차상륙함 2척에 중형굴삭기 등 19종 30대의 장비와 12종 35t의 물자를 싣고 들어가 잔해 제거와 학교·공공시설 재건, 의료 진료를 수행했으며 2014년 12월 임무를 마쳤다. 부대명 '아라우(Araw)'는 현지어로 태양·희망을 뜻한다.",
   legacy:"베니그노 아키노 필리핀 대통령은 태풍 피해 현장 첫 방문지로 아라우부대가 복구·완공한 타나완 센트럴초등학교를 골랐고, 부대장에게 한국말로 \"감사합니다\"라고 인사했다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/interviewView.do?newsId=148774692",
   yt:3, ytnote:"대통령이 피해 현장 첫 방문지로 '한국군이 지은 학교'를 고른 날",
   videos:[],
   related:[{t:"아라우 부대 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%95%84%EB%9D%BC%EC%9A%B0_%EB%B6%80%EB%8C%80"},
            {t:"평화유지·사회 재건…현지서 사랑받는 파병 장병들 / YTN", u:"https://www.youtube.com/watch?v=yXfRHL_huRk"}]},

  {cat:"culture", date:"2009-11-25", classic:true, aid:true, country:"OECD 개발원조위원회", econ:true, intl:true, pride:true,
   title:"한국, OECD DAC 24번째 회원국 가입…원조 받던 나라가 주는 나라가 된 세계 유일 사례",
   desc:"2009년 11월 25일 파리 OECD 본부에서 열린 개발원조위원회(DAC) 가입 심사 특별회의에서 회원국 전원 합의로 한국의 가입이 확정됐고, 2010년 1월 1일부터 24번째 정식 회원국으로 활동을 시작했다. 1961년 DAC 출범 이후 원조 수혜국에서 공여국으로 전환한 나라는 한국이 처음이자 유일하다. DAC 회원국들은 한국의 경험이 위원회에 새로운 활력이 될 것이라고 평가했다.",
   legacy:"이후 한국의 개발 경험은 아프리카·동남아 개도국이 직접 배우러 오는 커리큘럼이 됐고, '수원국에서 공여국으로'는 국제개발협력 현장에서 한국을 설명하는 고유명사가 됐다.",
   src:"외교부", url:"https://www.mofa.go.kr/www/brd/m_4080/view.do?seq=325276",
   yt:4, ytnote:"세계 어느 나라도 못 한 방향 전환 — 받던 나라에서 주는 나라로, 1961년 이후 유일",
   videos:[{t:"[개발협력주간] OECD DAC 가입 10주년 기념 SBS 일요특선 다큐멘터리 요약본", u:"https://www.youtube.com/watch?v=wSH8TEkByDw"},
           {t:"수원국에서 공여국이 된 세계 최초, 유일 국가 대한민국 [이슈 픽 쌤과 함께] | KBS", u:"https://www.youtube.com/watch?v=YofyNeUDmqk"},
           {t:"[국민리포트] 원조받던 한국.. 이제 원조하는 나라로!", u:"https://www.youtube.com/watch?v=NryuS0TQWRw"}],
   related:[{t:"선진공여국으로 우뚝 서다, OECD DAC 가입 (외교부 뉴포커스)", u:"https://www.mofa.go.kr/www/brd/m_4076/view.do?seq=325309"},
            {t:"한국, OECD DAC 가입 '선진국 대열 합류' (오마이뉴스)", u:"https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0001269063"}]},

  {cat:"culture", date:"2024-03-22", classic:true, aid:true, country:"에티오피아", econ:false, intl:true, pride:true,
   title:"6·25 참전 에티오피아 강뉴부대…70여 년 뒤 한국이 그 후손들을 찾아간다",
   desc:"1951년 하일레 셀라시에 황제는 황실근위대 6037명을 파병했고, 유엔군 강뉴부대로 253차례 전투에서 모두 승리했다. 그러나 귀국 후 정권이 바뀌며 참전용사들은 '한국을 도왔다'는 이유로 핍박받고 극빈층으로 밀려났다. 사단법인 따뜻한하루는 2016년부터 매년 이들의 가정을 찾아 생계비와 주거환경 개선을 지원하고, 2018년에는 후손들로 '강뉴합창단'을 창단해 장학사업을 이어오고 있다.",
   legacy:"현지에서 참전용사를 돕는 한국인은 '짜이(형제)'로 불리며, 강뉴합창단 후손들은 초청을 받아 한국을 찾아 임진각과 춘천 에티오피아 참전기념탑을 방문한다.",
   src:"한국일보", url:"https://www.hankookilbo.com/News/Read/A2024032210520005705",
   yt:5, ytnote:"한국을 도왔다는 이유로 가난해진 사람들 — 강뉴부대 후손을 찾아가는 보은 프로젝트",
   videos:[{t:"[호국보훈의 달 특집 다큐] 강뉴, 승리의 이름으로 — 에티오피아 참전용사들의 마지막 이야기", u:"https://www.youtube.com/watch?v=B3qNU6DrAdM"},
           {t:"\"할아버지가 구한 나라, 손녀를 구하다\"…해외 참전용사 손녀 수술 지원 / KBS", u:"https://www.youtube.com/watch?v=0FAjPMcWsk0"},
           {t:"한국을 도왔다는 이유로 핍박받은 에티오피아 참전용사들", u:"https://www.youtube.com/watch?v=3cUciXW4074"}],
   related:[{t:"\"참전용사 돕는 한국인은 '짜이'\"… 에티오피아에 퍼진 韓 온기 (국민일보)", u:"https://v.daum.net/v/WLX26shDYD"},
            {t:"LG, 6·25 에티오피아 참전용사 후손 '강뉴합창단' 방한 체류비 후원 (이데일리)", u:"https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=01262806645484016"}]},

  {cat:"culture", date:"2026-06-25", classic:true, aid:true, country:"콜롬비아", econ:false, intl:true, pride:true,
   title:"중남미 유일 6·25 파병국 콜롬비아…한국 대사관이 노병들을 직접 찾아간다",
   desc:"콜롬비아는 6·25 전쟁 당시 중남미에서 유일하게 지상군을 보낸 나라로, 현재 생존 참전용사는 380여 명으로 알려져 있다. 주콜롬비아 한국대사관은 6·25 발발 76주년을 맞아 수도 보고타를 벗어난 부카라망가 지역까지 '찾아가는 보훈 행사'를 열었다. 거동이 어려워 수도 행사에 오지 못하는 고령의 노병들을 한국 정부가 직접 찾아가는 방식이다.",
   legacy:"보고타에서 열린 기념식에는 참전용사 35명과 가족 등 120명이 참석해 '대한민국 국민 보은 메달'을 받았고, 콜롬비아 현지에서는 이들을 '잊혀진 영웅들'로 다시 조명하는 행사가 해마다 이어지고 있다.",
   src:"뉴스토마토", url:"http://www.newstomato.com/ReadNews.aspx?no=1305391",
   yt:3, ytnote:"수도에 못 오는 노병에게 한국이 찾아간다 — 중남미 유일 파병국 콜롬비아 보훈 현장",
   videos:[],
   related:[{t:"\"중남미 유일 파병국 콜롬비아, 한국전 참전 헌신 재조명\" (GOODTV)", u:"https://news.goodtv.co.kr/news/articleView.html?idxno=23923"},
            {t:"콜롬비아에서 대한민국 국민 보은 메달 헌정식 열려 (뉴스코리아)", u:"https://www.newskorea.ne.kr/news/articleView.html?idxno=12137"}]},

  {cat:"culture", date:"2011-01-31", classic:true, aid:true, country:"탄자니아·르완다 등", econ:false, intl:true, pride:true,
   title:"새마을운동, 74개국으로 수출…아프리카 오지 마을이 카사바 의존에서 벗어났다",
   desc:"한국의 1970년대 농촌개발 모델인 새마을운동이 개발 협력 프로그램으로 재설계돼 아프리카·아시아 저개발국에 전파됐다. 탄자니아 운지아냐 마을에서는 마을 지도자가 한국에서 새마을 교육을 받고 돌아온 뒤 주민들이 카사바 뿌리 의존에서 벗어나기 시작했고, 탄자니아 정부는 팡가니 지역에 새마을 방식 마을 조성 계획을 세웠다. 2015년에는 우간다·케냐·에티오피아·세네갈·말라위 등 아프리카 6개국 지역개발 전문가들이 영남대에서 새마을운동을 집중 학습했다.",
   legacy:"르완다는 새마을운동을 국가 농촌개발 모델로 벤치마킹했고, 아프리카 각국 공무원들이 지금도 한국에 연수를 오며 '새마을(Saemaul)'은 번역 없이 그대로 쓰이는 개발협력 용어가 됐다.",
   src:"세계일보", url:"https://www.segye.com/newsView/20110131001473",
   yt:4, ytnote:"'새마을'이 번역 없이 수출된 단어가 된 이유 — 르완다·탄자니아 현장 비교",
   videos:[{t:"한국의 새마을 운동을 도입해 대박난 르완다 마을 방문기 【아프리카6】", u:"https://www.youtube.com/watch?v=OkGSeDPzXyQ"},
           {t:"저개발국에 뿌리내린 '새마을운동' / YTN", u:"https://www.youtube.com/watch?v=26MeK2N0VQU"},
           {t:"기근에 시달리던 르완다가 한국 쌀 심었더니 벌어진 일 | 새마을운동 벤치마킹 #골라듄다큐", u:"https://www.youtube.com/watch?v=3cxfJBZVscs"}],
   related:[{t:"[전국] \"아프리카에 새마을운동을 전해주세요\" / YTN", u:"https://www.ytn.co.kr/_ln/0115_201511270142360461"},
            {t:"아프리카 6개국 지역개발 전문가, 영남대서 '새마을운동' 집중 학습 (영남대 국제개발협력원)", u:"https://www.yu.ac.kr/iidc/board/news.do?mode=view&articleNo=1221711"}]},

  {cat:"culture", date:"2026-06-16", classic:true, aid:true, country:"우간다·케냐·세네갈 등", econ:false, intl:true, pride:true,
   title:"K-벼재배기술이 연 아프리카 녹색혁명…우간다 벼 수확량 2배, 농가 소득 132%↑",
   desc:"농촌진흥청 KOPIA 우간다센터는 2013년 현지 국립농업연구청(NARO)과 함께 설립된 뒤 14개 협력 과제를 수행하고 농업전문가 22명을 파견해 현지 농업인 8666명을 교육했다. 시장가가 높은 향미벼 품종에 한국식 손이앙 기술과 공동재배 방식을 접목한 결과 벼 수확량은 2배 이상, 농가 소득은 132% 늘었다. KAFACI '아프리카 벼개발 파트너십'은 10년간 아프리카 15개국에 71개 벼품종을 개발·등록하고 23개국에서 벼 육종가 44명을 길러냈다.",
   legacy:"세네갈·감비아·기니·가나·카메룬·우간다·케냐 7개국에 'K-라이스벨트' 종자생산단지가 들어서면서, 한국이 만든 벼 품종이 아프리카 농민의 논에서 자국 이름으로 등록돼 재배되고 있다.",
   src:"농촌진흥청", url:"https://rda.go.kr/board/board.do?boardId=farmprmninfo&dataNo=100000811146&mode=updateCnt&prgId=day_farmprmninfoEntry",
   yt:3, ytnote:"한국이 만든 벼가 아프리카 이름으로 등록된다 — 수확량 2배의 기술 이전 구조",
   videos:[],
   related:[{t:"K농업 심은 우간다의 기적…벼 소득 132%·오렌지 소득 309%↑ (헤럴드경제)", u:"https://biz.heraldcorp.com/article/10814419"},
            {t:"K-벼 재배기술, 아프리카에 뿌리 내린다 (한국농어민신문)", u:"https://www.agrinet.co.kr/news/articleView.html?idxno=404902"}]},

  {cat:"culture", date:"2017-06-21", classic:true, aid:true, country:"에콰도르·탄자니아·카메룬 등", econ:true, intl:true, pride:true,
   title:"전자통관시스템 '유니패스' 수출…한국 행정 시스템이 개도국 세관을 바꿨다",
   desc:"관세청의 전자통관시스템 UNI-PASS는 2005년 카자흐스탄을 시작으로 에콰도르·탄자니아·카메룬 등 11개국에 3억4885만 달러 규모로 수출됐다. 특히 에콰도르 사업은 한국의 원조 자금이 아니라 상대국 자체 예산 2400만 달러로 체결돼, 원조가 아닌 실력으로 팔린 첫 사례로 평가된다. 수출입통관·징수·화물관리·관세환급·위험관리를 아우르는 관세행정 전 과정을 통째로 이식한다.",
   legacy:"도미니카공화국·과테말라·탄자니아 등 도입국 세관은 통관 시간이 줄고 부패 여지가 축소됐다고 평가했고, UNI-PASS는 개도국 세관 공무원이 한국으로 연수를 오는 '행정 한류'의 대표 품목이 됐다.",
   src:"한국일보", url:"https://www.hankookilbo.com/News/Read/201706211019855609",
   yt:3, ytnote:"원조가 아니라 제값 받고 판 행정 시스템 — 유니패스가 개도국 세관을 바꾼 방식",
   videos:[],
   related:[{t:"관세청, 에콰도르에 전자통관시스템 수출 성사 (대한민국 정책브리핑)", u:"https://www.korea.kr/news/policyBriefingView.do?newsId=148706600"},
            {t:"세계와 공유한다: 전자정부 시리즈 (2) 전자통관시스템 유니패스 (코리아넷)", u:"https://www.korean-culture.org/koreanet/view.do?seq=6492"}]}
];
