/* 국뽕 뉴스 데이터 — 자동 수집기가 이 파일만 수정한다.
   갱신일: 2026-09-26
   index.html 의 CSS/함수는 절대 건드리지 말 것. */
const NEWS = [
  {cat:"tech", date:"2026-09-14", econ:true, intl:true, country:"미국", size:"중견", company:"한미반도체", wclass:"글로벌수주", world:"일론 머스크가 160조 원을 쏟아붓는 미국 역사상 최대 반도체 공장 '테라팹'이 후공정 패키징 장비를 한국 중견기업에서 사기로 했다 — 국내 후공정 장비사가 이 공급망에 들어간 첫 사례다.", pride:true,
   title:"머스크의 160조 '테라팹', 첫 패키징 장비 발주서를 한국 중견기업에 보냈다",
   desc:"테슬라·스페이스X용 AI 칩을 자체 생산하려는 머스크의 '테라팹'이 한미반도체에 AI 시스템반도체용 첨단 패키징 장비 구매주문(PO)을 냈다. 테라팹은 첨단 로직·메모리·패키징·테스트를 수직계열화하는 총 1190억 달러(약 160조 원) 규모로, 미 반도체 역사상 최대 투자다. 국내 후공정 장비기업이 이 공급망에 진입한 것은 처음이다.",
   src:"한국경제", url:"https://www.hankyung.com/article/2026091438481",
   yt:5, ytnote:"머스크가 왜 '남의 장비'를 못 피하나 — AI 칩 후공정 병목을 장비 한 대 단위로 뜯어보기",
   videos:[{t:"한미반도체 \"HBM4 장비 전량 수주할 것…국내 경쟁상대 없어\"", u:"https://www.youtube.com/shorts/Rnd6-mRO7Ok"},
            {t:"한미반도체, 국내 1등 어드밴스드 패키징 장비 업체로 맹활약", u:"https://www.youtube.com/watch?v=rc-28FQJxvU"},
            {t:"머스크 손잡은 인텔…'테라팹' 인텔과 생산한다 | 삼프로TV", u:"https://www.youtube.com/watch?v=uYUrJvmqSDE"}],
   related:[{t:"한미반도체, 테라팹에 AI 시스템반도체 패키징 장비 공급 (한국경제)", u:"https://www.hankyung.com/article/202609143780i"},
            {t:"한미반도체, 테라팹과 AI 시스템반도체용 패키징 장비 공급 계약 (마켓잉크)", u:"https://www.market-ink.co.kr/news/articleView.html?idxno=11875"}]},

  {cat:"tech", date:"2026-09-14", econ:true, intl:true, country:"미국", size:"대기업", company:"한화에어로스페이스", wclass:"글로벌수주", world:"세계 최대 방산시장인 미국이 자국 육군의 차기 자주포 시제품을 한국 무기체계에 단독으로 맡겼다 — 국산 무기체계의 미 본토 진출 첫 사례다.", pride:true,
   title:"미 육군이 못 푼 자주포 숙제, K9에 맡겼다…10조 사업 시제품 단독 선정",
   desc:"미 육군이 한화의 현지법인 한화디펜스USA와 기동전술포(MTC) 시제품 계약을 체결했다. 우선 6문을 납품하고 12문을 추가 주문할 수 있는 1억30만 달러(약 1345억 원) 규모로, 최대 10조 원으로 추산되는 미 육군 차기 자주포 현대화 사업에서 K9 기반 차륜형 자주포가 시제품 제작·시험평가 사업자로 단독 선정됐다. 국산 무기체계가 세계 최대 방산시장 미국에 진출한 첫 사례다.",
   src:"한국경제", url:"https://www.hankyung.com/article/2026091422881",
   yt:5, ytnote:"'무기 수출국'에서 '무기 설계 기준을 파는 나라'로 — 미 육군 포병 현대화 사업 해부",
   videos:[{t:"\"K-방산 미국도 뚫었다\"‥K9, 미국 차세대 자주포 시제품 선정 / MBC 뉴스데스크", u:"https://www.youtube.com/watch?v=zxEYbiPN5Bc"},
            {t:"한화 K9, 미 육군 차기 자주포 사업 시제품 단독 선정｜지금 이 뉴스", u:"https://www.youtube.com/watch?v=bX_2VLCC49Q"},
            {t:"미국이 못 풀던 자주포 숙제, 결국 한국 한화 K9에 맡겼다", u:"https://www.youtube.com/shorts/AG7qGShs2ks"}],
   related:[{t:"美 포병 사업 정조준…신형 차륜형 자주포 'K9MH' 영상 공개 / 연합뉴스", u:"https://www.youtube.com/watch?v=fS3n-o2zSQ4"},
            {t:"미 육군, 차륜형 이어 2주 만에 K9 궤도형 자주포까지 도입 추진", u:"https://www.youtube.com/watch?v=uc7EJxanFYg"}]},

  {cat:"tech", date:"2026-09-10", econ:true, intl:true, country:"크로아티아", size:"대기업", company:"한화에어로스페이스", wclass:"글로벌수주", world:"미국 하이마스를 이미 보유한 나토 회원국이 장거리 정밀화력 추가 도입 상대로 한국 천무를 골랐다 — 폴란드·에스토니아·노르웨이에 이어 유럽 '천무 클럽'이 넷째 나라로 늘었다.", pride:true,
   title:"하이마스 쓰는 나토 회원국이 한국 천무를 샀다…크로아티아 6400억 계약",
   desc:"방위사업청과 한화에어로스페이스가 크로아티아 국방부와 약 6400억 원(4억3500만 유로) 규모의 다연장로켓 '천무(K239)' 수출 계약을 체결했다. 크로아티아는 미국 하이마스 8대를 이미 도입한 상태에서 천무 18대를 추가로 골라 2029년까지 전력화한다. 폴란드·에스토니아·노르웨이에 이어 발칸 반도 안보 요충지까지 '천무 클럽'이 넓어졌다.",
   src:"네이트뉴스(연합)", url:"https://news.nate.com/view/20260910n37218",
   yt:4, ytnote:"하이마스를 쓰는 나라가 천무를 또 사는 이유 — 발사대 한 대당 화력·단가 비교",
   videos:[{t:"\"또 터졌다!\" 크로아티아로 '천무 18문 수출 확정'", u:"https://www.youtube.com/watch?v=3CARYPRdKVc"},
            {t:"[K디펜스] 폴란드 개시.. 크로아도 가입.. K9 이어 두 번째 클럽 개설 / 머니투데이방송", u:"https://www.youtube.com/watch?v=ISA_kpGkpXc"},
            {t:"[W디펜스] 하이마스 안심 못해! \"크로아, 천무 대거 획득\" / 머니투데이방송", u:"https://www.youtube.com/watch?v=wrnP7lXxspI"}],
   related:[{t:"[한·에스토니아 방산 동맹] K9·천무 다음은 '전략적 파트너' (아시아타임즈)", u:"https://www.asiatime.co.kr/article/20260918500160"},
            {t:"천궁·K2 전차 이은 수출 쾌거…세계 시장서 존재감 커진 K방산", u:"https://m.news.nate.com/view/20260819n31223"}]},

  {cat:"tech", date:"2026-09-07", econ:true, intl:true, country:"미국", size:"대기업", company:"한미약품", wclass:"해외인정", world:"로슈·일라이릴리 같은 글로벌 빅파마가 자기 파이프라인을 채우려 한국 신약을 사 갔고, 올해 공개된 기술수출 계약 규모만 21조6637억 원에 달한다.", pride:true,
   title:"빅파마가 한국 신약을 사 간다…올해 기술수출만 21조6637억, 역대 최대",
   desc:"올해 국내 제약·바이오기업의 기술수출은 13건, 금액이 공개된 11건만 합쳐 21조6637억 원에 이른다. 한미약품은 비만 신약 'HM17321'을 로슈 자회사 제넨텍에 최대 3조5000억 원 규모로, 단장증후군 치료제 '소네페글루타이드'를 일라이릴리에 1조8973억 원 규모로 넘겼다. 선급금만 수천억 원대로, 후보물질이 아니라 '플랫폼 기술'을 사 간다는 점이 달라진 대목이다.",
   src:"머니투데이", url:"https://www.mt.co.kr/thebio/2026/09/07/2026090619570577205",
   yt:4, ytnote:"신약 하나로 3조를 받는다는 것 — 기술수출 계약서의 선급금·마일스톤 구조 읽는 법",
   videos:[{t:"K-바이오 기술 수출 역대 최대…핵심은 '플랫폼 기술' / 연합뉴스TV", u:"https://www.youtube.com/watch?v=DQv77NpNFYE"},
            {t:"한미약품, '살만 빼는' 비만약 터졌다…3.2조 기술수출 / 한국경제TV", u:"https://www.youtube.com/watch?v=_xieujEtoTQ"},
            {t:"한국 비만약 하나에 3.2조…한미약품 초대형 기술수출", u:"https://www.youtube.com/shorts/n-DnHTnvjEw"}],
   related:[{t:"기술수출 '30조' 꿈이 아니다…선급금만 수천억, 몸값 뛴 K-바이오 (머니투데이)", u:"https://www.mt.co.kr/thebio/2026/06/29/2026062821553849278"},
            {t:"K바이오, 신약 경쟁력 입증… 기술수출, 역대 최대 또 넘본다 (파이낸셜뉴스)", u:"https://www.fnnews.com/news/202608301753135370"}]},

  {cat:"tech", date:"2026-09-22", econ:true, intl:true, country:"미국", size:"중견", company:"두산퓨얼셀", wclass:"글로벌수주", world:"AI 데이터센터 전력난으로 발전 설비가 부족한 북미 시장이 한국 연료전지를 대량 구매해, 두산퓨얼셀의 해외 수주가 처음으로 1조 원을 넘겼다.", pride:true,
   title:"북미 전력난 뚫은 한국 연료전지…해외 수주 1조 돌파, 3222억 추가 계약",
   desc:"두산퓨얼셀이 미국 하이엑시엄과 3222억 원 규모 추가 공급 계약을 체결하며 해외 누적 수주 1조 원을 처음으로 넘겼다. AI 데이터센터가 몰고 온 북미 전력난 속에서 계통 증설 없이 현장에 바로 깔 수 있는 발전용 연료전지의 값이 뛰었고, 발전용 연료전지를 이 규모로 양산·납품할 수 있는 업체가 손에 꼽히는 상황이 계약 배경이다.",
   src:"글로벌이코노믹", url:"https://www.g-enews.com/article/Global-Biz/2026/09/202609220536554642fbbec65dfb_1",
   yt:4, ytnote:"AI가 전기를 먹어치우자 팔린 한국 발전기 — 데이터센터 전력난과 연료전지 쇼티지",
   videos:[{t:"가스터빈 다음 타자! 연료전지 쇼티지와 두산퓨얼셀 / 문경원 애널리스트", u:"https://www.youtube.com/watch?v=-XenwkrW28k"},
            {t:"[투자 핫플레이스] 국내 연료전지 1위업체 '두산퓨얼셀' / 머니투데이방송", u:"https://www.youtube.com/watch?v=n9ua0_8EvNM"},
            {t:"두산퓨얼셀 익산공장에선 무슨 일이? 수소연료전지 생산현장을 가다", u:"https://www.youtube.com/watch?v=G_4t2SddeV8"}],
   related:[{t:"[집중 분석] 미 빅테크가 주목한 수소 연료전지주 3가지 / 2026년 미국 수소에너지", u:"https://www.youtube.com/watch?v=WLXcHlZE-4c"},
            {t:"두산에너빌리티, 원전·SMR·가스터빈 삼각 성장 본격화 (한국경제)", u:"https://plus.hankyung.com/apps/newsinside.view?aid=202605070655a"}]},

  {cat:"tech", date:"2026-06-14", econ:true, intl:true, country:"스위스(WEF)", size:"스타트업", company:"에이로봇·RLWRLD·비트센싱", wclass:"해외인정", world:"세계경제포럼이 뽑는 '테크놀로지 파이오니어' 100곳에 한국 로봇·AI 스타트업 3곳이 동시에 들어갔다 — 구글·에어비앤비가 초기에 거친 그 명단이다.", pride:true,
   title:"WEF가 찍은 100개 기술기업에 한국 로봇 3곳…역대 최다로 이름 올렸다",
   desc:"세계경제포럼(WEF)의 '테크놀로지 파이오니어 2026' 100곳에 휴머노이드·피지컬 AI의 에이로봇, 로봇 파운데이션 모델의 RLWRLD, 레이더 센싱의 비트센싱이 동시에 선정됐다. AI·로봇·양자 분야에서 한국이 배출한 역대 최다 기록이다. 구글·페이팔·에어비앤비가 초기 스타트업 시절 거쳐 간 명단으로, 해외가 한국 딥테크 생태계의 체급을 인정한 신호로 읽힌다.",
   src:"글로벌이코노믹", url:"https://www.g-enews.com/article/Global-Biz/2026/06/202606142137591922bd56fbc3c_1",
   yt:4, ytnote:"'다음 유니콘은 로봇' — WEF가 한국 로봇 3곳을 고른 기준을 뜯어보기",
   videos:[{t:"RLDX-1 | Dexterity is Intelligence (RLWRLD)", u:"https://www.youtube.com/watch?v=KRD9yMqPKJw"},
            {t:"South Korea startup puts cameras on workers to teach AI robots", u:"https://www.youtube.com/watch?v=spRL3mokG0M"},
            {t:"Junghee Ryu & Carl Choi, RLWRLD on AI Robotics Infrastructure", u:"https://www.youtube.com/watch?v=5gYWimlmeLU"}],
   related:[{t:"에이로봇, 세계경제포럼(WEF) 테크놀로지 파이오니어 2026 선정 (로봇신문)", u:"https://www.irobotnews.com/news/articleView.html?idxno=46857"},
            {t:"리얼월드, WEF '테크놀로지 파이오니어 2026' 선정 (와우테일)", u:"https://wowtale.net/2026/06/16/260247/"}]},

  {cat:"tech", date:"2026-04-09", econ:true, intl:true, country:"벨기에", size:"대기업", company:"HD현대중공업", wclass:"세계최초", world:"탄소를 전혀 내뿜지 않는 암모니아를 주연료로 쓰는 상선을 세계에서 처음으로 완성해 실제 선주에게 인도했다 — 어느 나라도 아직 건조를 끝내지 못한 배다.", pride:true,
   title:"세계 첫 암모니아 추진선, 한국이 완성했다…탄소 배출 0 상선의 문을 열었다",
   desc:"HD현대중공업이 벨기에 엑스마르에서 수주한 암모니아 추진 중형 가스운반선 4척 가운데 1·2번 선박을 세계 최초로 건조 완료했다. 길이 190m·너비 30.4m급으로, 벨기에 도시 이름을 딴 '안트베르펜'과 '알롱'으로 명명됐다. 암모니아는 연소 시 탄소를 내뿜지 않지만 독성과 누출 위험이 커 실제 상선에 주연료로 얹은 사례가 없었고, 이 난제를 처음 통과한 곳이 한국이다.",
   src:"비즈워치", url:"https://news.bizwatch.co.kr/article/industry/2026/04/10/0002",
   yt:5, ytnote:"독가스로 배를 움직인다 — 암모니아 추진선의 누출 방지 설계를 도면으로 따라가기",
   videos:[{t:"HD현대, 암모니아 추진선 엔진 탑재 성공 '세계 최초'", u:"https://www.youtube.com/watch?v=RInaJdBgF_w"},
            {t:"HD현대미포, 세계 첫 암모니아 추진선 착공...연료 누출 완화로 안정성 확보", u:"https://www.youtube.com/watch?v=qzOEKFZx9eY"},
            {t:"[이것이 최고다] 세계 최초 건조한 최고 성능 LNG 추진 선박(feat. 수소 암모니아 선박)", u:"https://www.youtube.com/watch?v=BHfigL3a7YE"}],
   related:[{t:"HD현대중공업, 세계 최초 암모니아 추진선 건조 (머니투데이)", u:"https://www.mt.co.kr/industry/2026/04/09/2026040909001945339"},
            {t:"HD현대삼호, 초대형 암모니아 운반선 첫 인도 (뉴스핌)", u:"https://www.newspim.com/news/view/20260727001030"}]},

  {cat:"tech", date:"2026-04-22", econ:true, intl:true, country:"말레이시아", size:"대기업", company:"LIG넥스원", wclass:"글로벌수주", world:"함정용 대공유도무기 '해궁'의 첫 해외 수출을 따내 천궁에 이어 함대공 영역까지 한국산 유도무기를 사 가는 나라가 늘었다.", pride:true,
   title:"'해궁' 첫 수출 성공…말레이시아 함정에 한국산 함대공 미사일이 실린다",
   desc:"LIG 디펜스&에어로스페이스가 쿠알라룸푸르 방산전시회 'DSA 2026'에서 말레이시아 국방부와 함정용 대공방어 유도무기 '해궁(K-SAAM)' 수출 계약을 체결했다. 규모는 9400만 달러(약 1400억 원)로, 해궁의 첫 해외 수출이다. 천궁에 이어 함대공 유도무기까지 수출 품목에 올라, 동남아 해양 방공 시장에서 한국 유도무기의 영토가 넓어졌다.",
   src:"글로벌이코노믹", url:"https://www.g-enews.com/article/General-News/2026/04/202604221843372556e207547429_1",
   yt:3, ytnote:"배를 지키는 미사일은 왜 어려운가 — 해궁의 수직발사·종말유도 구조",
   videos:[],
   related:[{t:"천궁 이어 '해궁' 첫 수출 쐈다…말레이시아와 1400억 계약", u:"https://m.news.nate.com/view/20260422n25639"},
            {t:"K방산, 폴란드 MSPO 총출동…유럽 현지화 수요 공략", u:"https://m.news.nate.com/view/20260907n27902"}]},

  {cat:"kpop", date:"2026-08-17", econ:false, intl:true, country:"미국", pride:true,
   title:"스트레이 키즈, 빌보드 200 9연속 1위…비틀스 다음은 K팝이었다",
   desc:"스트레이 키즈가 새 미니앨범 '디스 앤드 댓'으로 미국 빌보드 200 정상에 올라 통산 9번째이자 데뷔 이후 9연속 1위를 달성했다. K팝 가수 최다 기록이며, 그룹 기준으로는 비틀스에 이어 빌보드 200 역사상 두 번째다. 2022년 '오디너리'부터 발표한 앨범이 단 한 번도 1위를 놓치지 않았다.",
   src:"서울신문", url:"https://www.seoul.co.kr/news/life/pop-culture/2026/08/17/20260817500064",
   yt:4, ytnote:"'9연속 1위'가 비틀스급이라는 말의 진짜 의미 — 빌보드 200 69년 기록을 표로 비교",
   videos:[{t:"스트레이 키즈, '빌보드 200' 9연속 1위‥비틀스 이어 그룹 2번째 / MBC 뉴스데스크", u:"https://www.youtube.com/watch?v=I3SkGI_z6wQ"},
            {t:"스트레이 키즈, 빌보드 9연속 1위…비틀스 이은 대기록 [잇슈 컬처] / KBS", u:"https://www.youtube.com/watch?v=8ZR4Qcis2XI"},
            {t:"남은 건 비틀스 기록뿐…스트레이 키즈, 빌보드 200 '9연속' 1위｜지금 이 장면", u:"https://www.youtube.com/watch?v=0iozubvLzv8"}],
   related:[{t:"제니, 빌보드 '핫 100' K팝 최장 톱10...BTS 기록 역전 (서울신문)", u:"https://www.seoul.co.kr/news/life/pop-culture/2026/09/15/20260915500197"},
            {t:"제니, 또 K-팝 새 역사…美 빌보드 종합 라디오 차트 정상 (헤럴드경제)", u:"https://www.heraldk.com/article/2026092222360425279"}]},

  {cat:"sports", date:"2026-09-20", econ:false, intl:true, country:"국제", pride:true,
   title:"성승민, 근대5종 아시안게임 첫 우승…한국 여자 선수가 처음 밟은 자리",
   desc:"성승민이 아이치·나고야 아시안게임 여자 근대5종 개인전에서 금메달을 따 한국 선수단 1호 금메달을 안겼다. 한국 여자 근대5종 사상 첫 아시안게임 개인전 우승이며, 승마 대신 장애물 경기가 도입된 뒤 열린 첫 대회의 초대 챔피언이기도 하다. 2024 파리 올림픽에서 아시아 여자 선수 최초로 입상(동메달)한 기량을 이어간 결과다.",
   src:"파이낸셜뉴스", url:"https://www.fnnews.com/news/202609201404425880",
   yt:3, ytnote:"5개 종목을 하루에 — 근대5종 장애물 도입이 판을 어떻게 바꿨나",
   videos:[],
   related:[{t:"'한국 첫 금메달 나왔다' … 성승민, 근대5종 여자 개인전 '첫 우승' (뉴데일리)", u:"https://www.newdaily.co.kr/site/data/html/2026/09/20/2026092000047.html"},
            {t:"카누, 남자 카약 4인승 500m 우승…한국 9번째 金 (뉴스1)", u:"https://www.news1.kr/sports/general-sport/6301194"}]},
  {cat:"sports", date:"2002-06-22", classic:true, econ:false, intl:false, pride:true, title:"2002 한일월드컵, 스페인 꺾고 아시아 최초 4강…'4강 신화'가 시작된 날",
   desc:"2002년 6월 22일 광주에서 열린 한일월드컵 8강전에서 한국이 스페인과 120분 혈투 끝에 승부차기 5-3으로 승리하며 아시아 국가 최초로 월드컵 4강에 올랐다. 이운재의 선방과 홍명보의 마지막 킥이 역사를 만들었고, 전국 거리에는 수백만 명의 붉은 물결이 쏟아졌다. 1954년 첫 출전 이후 48년 만에 본선 첫 승(폴란드전)을 거둔 대회이기도 하다.",
   src:"Wikipedia", url:"https://en.wikipedia.org/wiki/2002_FIFA_World_Cup",
   yt:5, ytnote:"승부차기 5-3, 그날의 120분을 다시 본다 — 4강 신화 완전 복기",
   videos:[{t:"'4강 신화', 호아킨 막은 이운재와 마무리한 홍명보 | 2002 FIFA 월드컵 8강 대한민국 VS 스페인", u:"https://www.youtube.com/watch?v=6Kr-_veieNw"},
           {t:"[리플레이] 대한민국이 아시아 최초로 월드컵 4강에 진출했던 순간", u:"https://www.youtube.com/watch?v=ibnH3f2UIY8"},
           {t:"\"4강 신화 탄생! 스페인을 승부차기에서 꺾습니다!\" 2002년 한일 월드컵 스페인전 / SBS", u:"https://www.youtube.com/watch?v=I9Owon_gk5E"}],
   related:[{t:"2002 한일월드컵 4강 신화 태극전사 재조명 (한국생활체육뉴스)", u:"http://www.kstnews.co.kr/news/articleView.html?idxno=21138"},
            {t:"[다시보는 2002 월드컵] 한국축구 4강 신화 하이라이트", u:"https://www.youtube.com/watch?v=kdYsF6rbMjs"}]},

  {cat:"culture", date:"2020-02-09", classic:true, econ:false, intl:true, country:"미국", pride:true, title:"'기생충', 아카데미 작품상 수상…92년 역사상 비영어 영화 최초",
   desc:"봉준호 감독의 '기생충'이 2020년 2월 9일(현지시각) 제92회 아카데미 시상식에서 작품상·감독상·각본상·국제장편영화상 4관왕에 올랐다. 비영어권 영화가 아카데미 작품상을 받은 것은 시상식이 시작된 이래 처음이며, 비영어 영화가 작품상과 감독상을 동시에 가져간 것도 사상 최초다. \"1인치 자막의 장벽을 넘으면\"이라는 봉 감독의 수상 소감은 그해 전 세계가 인용한 문장이 됐다.",
   src:"VOA 코리아", url:"https://www.voakorea.com/a/korea_korea-life_academyawards-parasite/6029036.html",
   yt:5, ytnote:"1인치 자막의 장벽 — '기생충'이 오스카 92년의 규칙을 깬 과정 복기",
   videos:[{t:"아카데미 작품상 '기생충' 호명되는 순간… / YTN", u:"https://www.youtube.com/watch?v=zGms9ShsjjA"},
           {t:"[제92회 아카데미] \"92년 오스카 벽 부쉈다!\"…'기생충' 작품상 수상 외신 반응은? / KBS", u:"https://www.youtube.com/watch?v=5tV-B8zJ6Y8"},
           {t:"'기생충' 작품상까지 4관왕…아카데미 92년 역사 깼다 | 뉴스A", u:"https://www.youtube.com/watch?v=aZKljkRE38w"}],
   related:[{t:"<기생충> 제92회 아카데미 시상식 4관왕, 2020 아카데미 최다 수상 (CJ 뉴스룸)", u:"https://cjnews.cj.net/%EA%B8%B0%EC%83%9D%EC%B6%A9-%EC%A0%9C92%ED%9A%8C-%EC%95%84%EC%B9%B4%EB%8D%B0%EB%AF%B8-%EC%8B%9C%EC%83%81%EC%8B%9D-%EC%9E%91%ED%92%88%EC%83%81-%EA%B0%90%EB%8F%85%EC%83%81-%EA%B0%81%EB%B3%B8/"},
            {t:"美 연예 매체 \"기생충, 역대 최고의 오스카 작품상 수상작\" / YTN", u:"https://www.youtube.com/watch?v=9JflQ6MW0ZE"}]},

  {cat:"sports", date:"2010-02-26", classic:true, econ:false, intl:false, pride:true, title:"김연아, 밴쿠버 올림픽 피겨 금메달…총점 228.56 세계신기록으로 아시아 벽을 깼다",
   desc:"2010년 2월 26일 밴쿠버 동계올림픽 피겨스케이팅 여자 싱글에서 김연아가 프리 150.06점, 총점 228.56점이라는 세계 최고기록으로 금메달을 차지했다. 한국인 최초의 올림픽 피겨 금메달이자, 쇼트·프리·총점 세계기록을 한 대회에서 모두 갈아치운 기록이었다. 2위와의 점수 차는 23점이 넘었고, 거슈윈 피아노 협주곡에 맞춘 그 연기는 지금도 피겨 역사상 최고의 프로그램으로 꼽힌다.",
   src:"VOA 코리아", url:"https://www.voakorea.com/a/a-35-2010-02-26-voa6-91416569/1329877.html",
   yt:5, ytnote:"228.56 — 16년이 지나도 회자되는 4분간의 완벽, 점수표로 뜯어보기",
   videos:[{t:"\"김연아! 피겨 여왕의 시대가 열립니다!\" 2010 밴쿠버 김연아 금메달 연기 (풀영상) / SBS", u:"https://www.youtube.com/watch?v=2DEDNW5Jq4Q"},
           {t:"김연아, 환상적인 연기로 세계 신기록을 달성했던 역사적인 순간｜2010 밴쿠버 프리프로그램", u:"https://www.youtube.com/watch?v=SJqdiEHs-xE"},
           {t:"[올림픽 공식] 김연아가 말하는 2010 밴쿠버 동계올림픽 금메달의 순간", u:"https://www.youtube.com/watch?v=R8Z97TLObnk"}],
   related:[{t:"Kim Yu-na, Women's Singles Figure Skating | Vancouver 2010 (Olympics.com)", u:"https://www.olympics.com/en/video/kim-yu-na-women-s-singles-figure-skating-vancouver-2010"},
            {t:"[오마이뉴스 선정 21세기 100대 뉴스] 김연아 밴쿠버 여자 피겨 금메달", u:"https://www.ohmynews.com/NWS_Web/Event/20th/at_pg.aspx?CNTN_CD=A0002612674"}]},

  {cat:"culture", date:"2022-09-12", classic:true, econ:false, intl:true, country:"미국", pride:true, title:"'오징어 게임', 에미상 감독상·남우주연상 수상…74년 역사상 비영어 드라마 최초",
   desc:"2022년 9월 12일(현지시각) 제74회 프라임타임 에미상에서 넷플릭스 '오징어 게임'의 황동혁 감독이 드라마 시리즈 감독상을, 이정재가 남우주연상을 받았다. 비영어권 드라마가 에미상 감독상과 남우주연상을 수상한 것은 74년 역사상 처음이며, 작품상 후보에 오른 것도 비영어 드라마로는 최초였다. 이정재는 한국어로 수상 소감을 남기며 국내 시청자들과 기쁨을 나눴다.",
   src:"MBC 뉴스", url:"https://imnews.imbc.com/replay/2022/nw1200/article/6407256_35715.html",
   yt:5, ytnote:"자막의 벽을 두 번째로 무너뜨린 밤 — '오징어 게임'이 에미상에서 바꾼 규칙",
   videos:[{t:"'오징어 게임' 에미상서 이정재 남우주연상, 황동혁 감독상 수상 / KBS 2022.09.13.", u:"https://www.youtube.com/watch?v=CpRcvHlfWV8"},
           {t:"에미상 휩쓴 '오징어 게임'‥비영어권 최초 (2022.09.14/뉴스투데이/MBC)", u:"https://www.youtube.com/watch?v=6z-dPWLnLmI"},
           {t:"'오징어게임' 이정재·황동혁 센스 만점 수상 소감 (현장영상) / SBS", u:"https://www.youtube.com/watch?v=qSbCd_5LqYg"}],
   related:[{t:"'오징어게임', 비영어 드라마 최초 에미상 작품상 후보 (경향신문)", u:"https://www.khan.co.kr/article/202207130751001"},
            {t:"'오징어 게임' 미국 에미상 감독상·남우주연상 수상…비영어권 최초 / KBS", u:"https://www.youtube.com/watch?v=USsIy6EjGMQ"}]},

  // ── 국제기여 아카이브: 한국이 다른 나라를 도운 이야기 ──
  {cat:"culture", date:"1999-10-04", classic:true, aid:true, country:"동티모르", econ:false, intl:true, pride:true,
   title:"동티모르 상록수부대…구스마오 대통령이 취임 후 가장 먼저 찾은 나라가 한국이었다",
   desc:"1999년 10월 파병된 상록수부대는 동티모르 13개 군 가운데 로스팔로스와 오쿠시 2개 군에 각각 2년씩 주둔하며 4년간 지역 안정화를 이끌었다. 파견국 중 유일하게 대민지원 작전 '블루엔젤'을 별도로 전개해 동티모르 정부와 유엔군사령부로부터 '가장 모범적인 부대'라는 평가를 받았다. 임무 수행 중 순직한 부대원 5명의 추모식은 지금도 현지 오에쿠시에서 열린다.",
   legacy:"2002년 6월 취임한 구스마오 대통령은 외국 가운데 한국을 가장 먼저 방문해 파병에 사의를 표했고, 상록수부대가 주둔했던 지역 주민들을 \"동티모르인 가운데 가장 복 받은 주민\"이라고 표현했다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/policyNewsView.do?newsId=50002709",
   yt:5, ytnote:"한 나라의 대통령이 취임 후 첫 외국 방문지로 한국을 고른 이유 — 상록수부대 4년의 기록",
   videos:[{t:"[영상] 육군 상록수부대 동티모르 파병 (1999.10.04)", u:"https://www.youtube.com/watch?v=YQL3LyKkBZQ"},
           {t:"한국군 최초 PKO 상록수 부대 | 소말리아인이 놀란 상록수 부대", u:"https://www.youtube.com/watch?v=ZHQcd46Je_A"},
           {t:"동티모르 상록수부대 순직 15주기 추모식 열려 / YTN KOREAN", u:"https://www.youtube.com/watch?v=UCXMSncc8eA"}],
   related:[{t:"상록수부대(常綠樹部隊) — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0068134"},
            {t:"상록수부대 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%83%81%EB%A1%9D%EC%88%98%EB%B6%80%EB%8C%80"}]},

  {cat:"culture", date:"2007-07-19", classic:true, aid:true, country:"레바논", econ:false, intl:true, pride:true,
   title:"레바논 동명부대 18년…남부 티르 주민들이 부르는 이름은 '신이 준 선물'",
   desc:"2007년 6월 창설돼 7월 레바논 남부 티르 지역에 전개된 동명부대는 국군 해외파병 부대 가운데 최장수 부대다. UNIFIL 서부여단 소속으로 정전 감시와 폭발물 제거를 맡는 동시에, 의료지원과 학교·공공시설 개보수, 주민 일자리 창출형 민사작전을 이어왔다. 이스라엘-헤즈볼라 충돌이 반복되는 최전선에서 18년째 자리를 지키고 있다.",
   legacy:"현지 주민들은 동명부대를 '신이 준 선물'이라 부르며, 부대의 민군작전은 레바논 남부 안정화에 크게 기여한 것으로 평가받는다. 부대가 운영한 태권도 교실 출신 '레바논 태권도 키즈'는 지역의 상징이 됐다.",
   src:"한국민족문화대백과사전", url:"https://encykorea.aks.ac.kr/Article/E0080634",
   yt:4, ytnote:"18년을 한 도시에 머문 군대 — 티르 아이들이 한국어로 태권도 구령을 외치기까지",
   videos:[{t:"폭발물 제거, 의료 지원, 태권도 지도까지…레바논 티르의 동명부대 (KBS 2016.10.01)", u:"https://www.youtube.com/watch?v=r_-EVatiKPQ"},
           {t:"피쓰 투 레바논 — 국제평화를 지키는 그들의 이야기 #동명부대 #UNIFIL", u:"https://www.youtube.com/watch?v=7U01CCkV_T0"},
           {t:"레바논의 푸른 희망 동명부대 2부 [강군365 200회]", u:"https://www.youtube.com/watch?v=EXq55Sup3l4"}],
   related:[{t:"대한민국 레바논 평화 유지단 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EB%A0%88%EB%B0%94%EB%85%BC_%ED%8F%89%ED%99%94_%EC%9C%A0%EC%A7%80%EB%8B%A8"},
            {t:"내가 바로 레바논 태권도 키즈 #동명부대", u:"https://www.youtube.com/shorts/BuHdSrXD8TI"}]},

  {cat:"culture", date:"2013-04-01", classic:true, aid:true, country:"남수단", econ:false, intl:true, pride:true,
   title:"남수단 한빛부대, 307km '생명의 도로'…피보르 시장 \"남수단이 번영한 건 한빛부대 덕\"",
   desc:"2013년 남수단 종글레이주 보르에 전개된 한빛부대는 UNMISS 소속으로 12년 넘게 재건지원 임무를 이어오고 있다. 보르~피보르~아코보를 잇는 307km 주보급로를 보수해 현지 물류의 생명줄을 만들었고, 2014년에는 보르시에 르왈딧 초등학교를 세웠다. 한빛직업학교와 한빛농장으로 기술을 전수하고 한국어·태권도 교실도 운영한다.",
   legacy:"피보르 시장 보요이 골라는 \"남수단이 번영하고 무역이 활성화된 것은 한빛부대가 수백km 도로를 건설한 재건 작전 덕분\"이라 말했고, 구무룩 마을 위원장은 \"아이들과 여성, 노인 모두가 나아진 도로를 보고 행복해했다\"고 감사를 전했다. 현지에서 한빛부대의 별명은 '신이 내린 선물'이다.",
   src:"세계일보", url:"https://www.segye.com/newsView/20250330507167",
   yt:5, ytnote:"307km 흙길이 나라의 무역로가 되기까지 — 남수단이 한국군을 '신이 내린 선물'이라 부르는 이유",
   videos:[{t:"남수단 신이 내린 선물｜한빛부대 파병 10주년을 기하며", u:"https://www.youtube.com/watch?v=krCCOx5po3s"},
           {t:"[한빛부대 16진] 남수단 주민에 '생명의 도로' 선물", u:"https://www.youtube.com/watch?v=c0dgHNY7hxs"},
           {t:"\"신이 내린 선물\"…국군의 날 기념 해외파병부대(청해·아크·한빛·동명) 활약상 공개", u:"https://www.youtube.com/watch?v=y8IXVo2WMDQ"}],
   related:[{t:"남수단 국민은 왜 한빛부대를 \"신이 내린 선물\"이라 찬사 보낼까 (문화일보)", u:"https://news.nate.com/view/20250330n04489"},
            {t:"남수단 한빛부대 — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0080633"}]},

  {cat:"culture", date:"2010-03-08", classic:true, aid:true, country:"아이티", econ:false, intl:true, pride:true,
   title:"아이티 단비부대, 철수하며 110억원짜리 주둔지를 통째로 아이티에 넘겼다",
   desc:"2010년 1월 대지진 직후 창설된 단비부대는 3월 8일 레오간에 도착해 2년 9개월간 잔해 제거, 도로 복구, 하천 정비, 우물 개발을 수행했다. 공식 임무가 아니었는데도 난민들에게 우물을 파주고 마을과 학교를 지었으며, 콜레라 방역과 난민촌 진료를 병행했다. 2012년 12월 철수하면서 110억원 규모의 주둔지 시설물 전부를 아이티 정부에 무상 공여하고 떠났다.",
   legacy:"부대가 세운 초등학교와 우물, 그리고 통째로 남기고 간 주둔지 시설은 지금도 레오간에서 사용되고 있다 — 한국군이 '단비'라는 이름 그대로 기억되는 이유다.",
   src:"YTN", url:"https://m.ytn.co.kr/news_view.amp.php?param=0101_201212241602370439",
   yt:3, ytnote:"떠나면서 기지를 통째로 주고 온 부대 — 아이티 '단비'의 2년 9개월",
   videos:[],
   related:[{t:"대한민국 아이티 재건지원단 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EC%95%84%EC%9D%B4%ED%8B%B0_%EC%9E%AC%EA%B1%B4%EC%A7%80%EC%9B%90%EB%8B%A8"},
            {t:"아이티 단비부대, 즐겁고 훈훈한 태권도 현장", u:"https://www.youtube.com/watch?v=_HdWrVphUSM"}]},

  {cat:"culture", date:"2011-01-21", classic:true, aid:true, country:"미얀마·인도네시아", econ:false, intl:true, pride:true,
   title:"아덴만 여명작전…구출된 인질 21명 중 13명은 미얀마·인도네시아 선원이었다",
   desc:"2011년 1월 15일 소말리아 해적에 피랍된 삼호주얼리호를 구하기 위해 청해부대가 작전에 들어가, 피랍 6일 만인 1월 21일 해군특수전전단(UDT/SEAL)이 선박을 급습했다. 해적 8명을 사살하고 5명을 생포하며 인질 21명 전원을 무사히 구출했는데, 이 가운데 미얀마인 11명과 인도네시아인 2명 등 13명이 외국인 선원이었다. 미국·오만·파키스탄 등 다국적 함정이 작전을 지원했다.",
   legacy:"한국 해군이 자국민뿐 아니라 동남아 선원 13명의 목숨까지 함께 구해낸 이 작전은 해양 안보·인도주의 군사작전의 모범 사례로 국제 사회에서 거론된다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/policyNewsView.do?newsId=148726097",
   yt:5, ytnote:"구출된 21명 중 13명은 한국인이 아니었다 — 아덴만 여명작전을 다시 보는 관점",
   videos:[{t:"[국방부] 다큐멘터리 — 아덴만 여명작전 7일간의 기록", u:"https://www.youtube.com/watch?v=ywyBl1KaICw"},
           {t:"삼호주얼리호에 피랍된 21명의 선원들을 구하라! #벌거벗은세계사 EP.31 | tvN", u:"https://www.youtube.com/watch?v=AEjuA2zIPdY"},
           {t:"청해부대 아덴만 여명작전 영상 (S. Korean Navy Rescued Hostages from Somalia Pirates)", u:"https://www.youtube.com/watch?v=VrfvHWUCr_0"}],
   related:[{t:"아덴만 여명 작전 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%95%84%EB%8D%B4%EB%A7%8C_%EC%97%AC%EB%AA%85_%EC%9E%91%EC%A0%84"},
            {t:"소말리아 해역 청해부대 — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0080635"}]},

  {cat:"culture", date:"2023-02-08", classic:true, aid:true, country:"튀르키예", econ:false, intl:true, pride:true,
   title:"튀르키예 대지진, 한국 긴급구호대 118명…6·25 때 우리를 도운 그 땅에서 생존자를 꺼냈다",
   desc:"2023년 2월 6일 대지진 직후 외교부·국방부·소방청·KOICA로 구성된 해외긴급구호대(KDRT) 118명이 파견돼 2월 8일 오전 가지안테프 공항에 도착했다. 튀르키예 정부 요청에 따라 하타이주 안타키아를 중점 구조지역으로 선정했고, 2월 9일 구조 개시 90분 만에 첫 생존자를 구해낸 뒤 7시간 만에 5명을 구조했다. 구호대는 3진까지 이어져 3월까지 구조·재건 활동을 계속했다.",
   legacy:"튀르키예는 6·25 때 미국 다음으로 많은 병력을 보낸 '형제의 나라'이며, 한국 구호대가 활동한 지역은 당시 튀르키예군이 한국으로 떠났던 이스켄데룬 인근이었다 — 72년 만에 같은 항구에서 방향만 바뀐 셈이다.",
   src:"외교부", url:"https://www.mofa.go.kr/www/brd/m_4076/view.do?seq=369765",
   yt:5, ytnote:"72년 전 그 항구에서 — 형제의 나라에 진 빚을 갚으러 간 118명",
   videos:[{t:"한국 긴급 구호대, 튀르키예 지진 현장서 생존자 첫 구조", u:"https://www.youtube.com/watch?v=56RwgfnlCkk"},
           {t:"\"튀르키예, 형제의 나라\"…긴급구호대 110명 급파 | 뉴스A", u:"https://www.youtube.com/watch?v=uJOXF9bv4aE"},
           {t:"총 8명의 생존자를 구조하다! 튀르키예·시리아 대지진에서 활약한 대한민국 긴급구호대", u:"https://www.youtube.com/watch?v=KfVzVure7aM"}],
   related:[{t:"정부 긴급구호대 튀르키예 지진 현장 도착해 수색·구조활동 개시 (경향신문)", u:"https://m.khan.co.kr/politics/defense-diplomacy/article/202302081620001"},
            {t:"튀르키예 지진 피해 지원 대한민국 해외긴급구호대(KDRT) 3진 복귀 (외교부)", u:"https://www.mofa.go.kr/www/brd/m_4080/view.do?seq=373500"}]},

  {cat:"culture", date:"2013-12-09", classic:true, aid:true, country:"필리핀", econ:false, intl:true, pride:true,
   title:"태풍 하이옌 폐허의 필리핀에 520명 아라우부대…아키노 대통령이 한국말로 \"감사합니다\"",
   desc:"2013년 11월 슈퍼태풍 하이옌으로 초토화된 필리핀 타클로반에 12월 9일부터 520여 명 규모의 아라우부대가 전개됐다. 전차상륙함 2척에 중형굴삭기 등 19종 30대의 장비와 12종 35t의 물자를 싣고 들어가 잔해 제거와 학교·공공시설 재건, 의료 진료를 수행했으며 2014년 12월 임무를 마쳤다. 부대명 '아라우(Araw)'는 현지어로 태양·희망을 뜻한다.",
   legacy:"베니그노 아키노 필리핀 대통령은 태풍 피해 현장 첫 방문지로 아라우부대가 복구·완공한 타나완 센트럴초등학교를 골랐고, 부대장에게 한국말로 \"감사합니다\"라고 인사했다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/interviewView.do?newsId=148774692",
   yt:3, ytnote:"대통령이 피해 현장 첫 방문지로 '한국군이 지은 학교'를 고른 날",
   videos:[],
   related:[{t:"아라우 부대 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%95%84%EB%9D%BC%EC%9A%B0_%EB%B6%80%EB%8C%80"},
            {t:"평화유지·사회 재건…현지서 사랑받는 파병 장병들 / YTN", u:"https://www.youtube.com/watch?v=yXfRHL_huRk"}]},

  {cat:"culture", date:"2009-11-25", classic:true, aid:true, country:"OECD 개발원조위원회", econ:true, intl:true, pride:true,
   title:"한국, OECD DAC 24번째 회원국 가입…원조 받던 나라가 주는 나라가 된 세계 유일 사례",
   desc:"2009년 11월 25일 파리 OECD 본부에서 열린 개발원조위원회(DAC) 가입 심사 특별회의에서 회원국 전원 합의로 한국의 가입이 확정됐고, 2010년 1월 1일부터 24번째 정식 회원국으로 활동을 시작했다. 1961년 DAC 출범 이후 원조 수혜국에서 공여국으로 전환한 나라는 한국이 처음이자 유일하다. DAC 회원국들은 한국의 경험이 위원회에 새로운 활력이 될 것이라고 평가했다.",
   legacy:"이후 한국의 개발 경험은 아프리카·동남아 개도국이 직접 배우러 오는 커리큘럼이 됐고, '수원국에서 공여국으로'는 국제개발협력 현장에서 한국을 설명하는 고유명사가 됐다.",
   src:"외교부", url:"https://www.mofa.go.kr/www/brd/m_4080/view.do?seq=325276",
   yt:4, ytnote:"세계 어느 나라도 못 한 방향 전환 — 받던 나라에서 주는 나라로, 1961년 이후 유일",
   videos:[{t:"[개발협력주간] OECD DAC 가입 10주년 기념 SBS 일요특선 다큐멘터리 요약본", u:"https://www.youtube.com/watch?v=wSH8TEkByDw"},
           {t:"수원국에서 공여국이 된 세계 최초, 유일 국가 대한민국 [이슈 픽 쌤과 함께] | KBS", u:"https://www.youtube.com/watch?v=YofyNeUDmqk"},
           {t:"[국민리포트] 원조받던 한국.. 이제 원조하는 나라로!", u:"https://www.youtube.com/watch?v=NryuS0TQWRw"}],
   related:[{t:"선진공여국으로 우뚝 서다, OECD DAC 가입 (외교부 뉴포커스)", u:"https://www.mofa.go.kr/www/brd/m_4076/view.do?seq=325309"},
            {t:"한국, OECD DAC 가입 '선진국 대열 합류' (오마이뉴스)", u:"https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0001269063"}]},

  {cat:"culture", date:"2024-03-22", classic:true, aid:true, country:"에티오피아", econ:false, intl:true, pride:true,
   title:"6·25 참전 에티오피아 강뉴부대…70여 년 뒤 한국이 그 후손들을 찾아간다",
   desc:"1951년 하일레 셀라시에 황제는 황실근위대 6037명을 파병했고, 유엔군 강뉴부대로 253차례 전투에서 모두 승리했다. 그러나 귀국 후 정권이 바뀌며 참전용사들은 '한국을 도왔다'는 이유로 핍박받고 극빈층으로 밀려났다. 사단법인 따뜻한하루는 2016년부터 매년 이들의 가정을 찾아 생계비와 주거환경 개선을 지원하고, 2018년에는 후손들로 '강뉴합창단'을 창단해 장학사업을 이어오고 있다.",
   legacy:"현지에서 참전용사를 돕는 한국인은 '짜이(형제)'로 불리며, 강뉴합창단 후손들은 초청을 받아 한국을 찾아 임진각과 춘천 에티오피아 참전기념탑을 방문한다.",
   src:"한국일보", url:"https://www.hankookilbo.com/News/Read/A2024032210520005705",
   yt:5, ytnote:"한국을 도왔다는 이유로 가난해진 사람들 — 강뉴부대 후손을 찾아가는 보은 프로젝트",
   videos:[{t:"[호국보훈의 달 특집 다큐] 강뉴, 승리의 이름으로 — 에티오피아 참전용사들의 마지막 이야기", u:"https://www.youtube.com/watch?v=B3qNU6DrAdM"},
           {t:"\"할아버지가 구한 나라, 손녀를 구하다\"…해외 참전용사 손녀 수술 지원 / KBS", u:"https://www.youtube.com/watch?v=0FAjPMcWsk0"},
           {t:"한국을 도왔다는 이유로 핍박받은 에티오피아 참전용사들", u:"https://www.youtube.com/watch?v=3cUciXW4074"}],
   related:[{t:"\"참전용사 돕는 한국인은 '짜이'\"… 에티오피아에 퍼진 韓 온기 (국민일보)", u:"https://v.daum.net/v/WLX26shDYD"},
            {t:"LG, 6·25 에티오피아 참전용사 후손 '강뉴합창단' 방한 체류비 후원 (이데일리)", u:"https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=01262806645484016"}]},

  {cat:"culture", date:"2026-06-25", classic:true, aid:true, country:"콜롬비아", econ:false, intl:true, pride:true,
   title:"중남미 유일 6·25 파병국 콜롬비아…한국 대사관이 노병들을 직접 찾아간다",
   desc:"콜롬비아는 6·25 전쟁 당시 중남미에서 유일하게 지상군을 보낸 나라로, 현재 생존 참전용사는 380여 명으로 알려져 있다. 주콜롬비아 한국대사관은 6·25 발발 76주년을 맞아 수도 보고타를 벗어난 부카라망가 지역까지 '찾아가는 보훈 행사'를 열었다. 거동이 어려워 수도 행사에 오지 못하는 고령의 노병들을 한국 정부가 직접 찾아가는 방식이다.",
   legacy:"보고타에서 열린 기념식에는 참전용사 35명과 가족 등 120명이 참석해 '대한민국 국민 보은 메달'을 받았고, 콜롬비아 현지에서는 이들을 '잊혀진 영웅들'로 다시 조명하는 행사가 해마다 이어지고 있다.",
   src:"뉴스토마토", url:"http://www.newstomato.com/ReadNews.aspx?no=1305391",
   yt:3, ytnote:"수도에 못 오는 노병에게 한국이 찾아간다 — 중남미 유일 파병국 콜롬비아 보훈 현장",
   videos:[],
   related:[{t:"\"중남미 유일 파병국 콜롬비아, 한국전 참전 헌신 재조명\" (GOODTV)", u:"https://news.goodtv.co.kr/news/articleView.html?idxno=23923"},
            {t:"콜롬비아에서 대한민국 국민 보은 메달 헌정식 열려 (뉴스코리아)", u:"https://www.newskorea.ne.kr/news/articleView.html?idxno=12137"}]},

  {cat:"culture", date:"2011-01-31", classic:true, aid:true, country:"탄자니아·르완다 등", econ:false, intl:true, pride:true,
   title:"새마을운동, 74개국으로 수출…아프리카 오지 마을이 카사바 의존에서 벗어났다",
   desc:"한국의 1970년대 농촌개발 모델인 새마을운동이 개발 협력 프로그램으로 재설계돼 아프리카·아시아 저개발국에 전파됐다. 탄자니아 운지아냐 마을에서는 마을 지도자가 한국에서 새마을 교육을 받고 돌아온 뒤 주민들이 카사바 뿌리 의존에서 벗어나기 시작했고, 탄자니아 정부는 팡가니 지역에 새마을 방식 마을 조성 계획을 세웠다. 2015년에는 우간다·케냐·에티오피아·세네갈·말라위 등 아프리카 6개국 지역개발 전문가들이 영남대에서 새마을운동을 집중 학습했다.",
   legacy:"르완다는 새마을운동을 국가 농촌개발 모델로 벤치마킹했고, 아프리카 각국 공무원들이 지금도 한국에 연수를 오며 '새마을(Saemaul)'은 번역 없이 그대로 쓰이는 개발협력 용어가 됐다.",
   src:"세계일보", url:"https://www.segye.com/newsView/20110131001473",
   yt:4, ytnote:"'새마을'이 번역 없이 수출된 단어가 된 이유 — 르완다·탄자니아 현장 비교",
   videos:[{t:"한국의 새마을 운동을 도입해 대박난 르완다 마을 방문기 【아프리카6】", u:"https://www.youtube.com/watch?v=OkGSeDPzXyQ"},
           {t:"저개발국에 뿌리내린 '새마을운동' / YTN", u:"https://www.youtube.com/watch?v=26MeK2N0VQU"},
           {t:"기근에 시달리던 르완다가 한국 쌀 심었더니 벌어진 일 | 새마을운동 벤치마킹 #골라듄다큐", u:"https://www.youtube.com/watch?v=3cxfJBZVscs"}],
   related:[{t:"[전국] \"아프리카에 새마을운동을 전해주세요\" / YTN", u:"https://www.ytn.co.kr/_ln/0115_201511270142360461"},
            {t:"아프리카 6개국 지역개발 전문가, 영남대서 '새마을운동' 집중 학습 (영남대 국제개발협력원)", u:"https://www.yu.ac.kr/iidc/board/news.do?mode=view&articleNo=1221711"}]},

  {cat:"culture", date:"2026-06-16", classic:true, aid:true, country:"우간다·케냐·세네갈 등", econ:false, intl:true, pride:true,
   title:"K-벼재배기술이 연 아프리카 녹색혁명…우간다 벼 수확량 2배, 농가 소득 132%↑",
   desc:"농촌진흥청 KOPIA 우간다센터는 2013년 현지 국립농업연구청(NARO)과 함께 설립된 뒤 14개 협력 과제를 수행하고 농업전문가 22명을 파견해 현지 농업인 8666명을 교육했다. 시장가가 높은 향미벼 품종에 한국식 손이앙 기술과 공동재배 방식을 접목한 결과 벼 수확량은 2배 이상, 농가 소득은 132% 늘었다. KAFACI '아프리카 벼개발 파트너십'은 10년간 아프리카 15개국에 71개 벼품종을 개발·등록하고 23개국에서 벼 육종가 44명을 길러냈다.",
   legacy:"세네갈·감비아·기니·가나·카메룬·우간다·케냐 7개국에 'K-라이스벨트' 종자생산단지가 들어서면서, 한국이 만든 벼 품종이 아프리카 농민의 논에서 자국 이름으로 등록돼 재배되고 있다.",
   src:"농촌진흥청", url:"https://rda.go.kr/board/board.do?boardId=farmprmninfo&dataNo=100000811146&mode=updateCnt&prgId=day_farmprmninfoEntry",
   yt:3, ytnote:"한국이 만든 벼가 아프리카 이름으로 등록된다 — 수확량 2배의 기술 이전 구조",
   videos:[],
   related:[{t:"K농업 심은 우간다의 기적…벼 소득 132%·오렌지 소득 309%↑ (헤럴드경제)", u:"https://biz.heraldcorp.com/article/10814419"},
            {t:"K-벼 재배기술, 아프리카에 뿌리 내린다 (한국농어민신문)", u:"https://www.agrinet.co.kr/news/articleView.html?idxno=404902"}]},

  {cat:"culture", date:"2017-06-21", classic:true, aid:true, country:"에콰도르·탄자니아·카메룬 등", econ:true, intl:true, pride:true,
   title:"전자통관시스템 '유니패스' 수출…한국 행정 시스템이 개도국 세관을 바꿨다",
   desc:"관세청의 전자통관시스템 UNI-PASS는 2005년 카자흐스탄을 시작으로 에콰도르·탄자니아·카메룬 등 11개국에 3억4885만 달러 규모로 수출됐다. 특히 에콰도르 사업은 한국의 원조 자금이 아니라 상대국 자체 예산 2400만 달러로 체결돼, 원조가 아닌 실력으로 팔린 첫 사례로 평가된다. 수출입통관·징수·화물관리·관세환급·위험관리를 아우르는 관세행정 전 과정을 통째로 이식한다.",
   legacy:"도미니카공화국·과테말라·탄자니아 등 도입국 세관은 통관 시간이 줄고 부패 여지가 축소됐다고 평가했고, UNI-PASS는 개도국 세관 공무원이 한국으로 연수를 오는 '행정 한류'의 대표 품목이 됐다.",
   src:"한국일보", url:"https://www.hankookilbo.com/News/Read/201706211019855609",
   yt:3, ytnote:"원조가 아니라 제값 받고 판 행정 시스템 — 유니패스가 개도국 세관을 바꾼 방식",
   videos:[],
   related:[{t:"관세청, 에콰도르에 전자통관시스템 수출 성사 (대한민국 정책브리핑)", u:"https://www.korea.kr/news/policyBriefingView.do?newsId=148706600"},
            {t:"세계와 공유한다: 전자정부 시리즈 (2) 전자통관시스템 유니패스 (코리아넷)", u:"https://www.korean-culture.org/koreanet/view.do?seq=6492"}]}
];
