/* 국뽕 뉴스 데이터 — 자동 수집기가 이 파일만 수정한다.
   갱신일: 2026-09-25
   index.html 의 CSS/함수는 절대 건드리지 말 것. */
const NEWS = [
  {cat:"tech", date:"2026-09-24", econ:true, intl:true, country:"미국", size:"대기업", company:"삼성전자", wclass:"세계최초", world:"차세대 모바일 메모리 LPDDR6를 퀄컴의 다음 세대 AP에서 업계 최초로 검증 완료해, 전 세계 AI 스마트폰이 쓸 메모리 규격의 기준점을 한국이 먼저 확정했다.", pride:true,
   title:"AI폰 메모리도 한국이 먼저 끝냈다…삼성, 퀄컴 차세대 AP서 LPDDR6 업계 최초 검증",
   desc:"삼성전자가 차세대 모바일 D램 규격인 LPDDR6를 퀄컴의 다음 세대 모바일 AP에서 업계 최초로 검증 완료했다. 스마트폰이 온디바이스 AI로 넘어가면서 메모리에 요구되는 것이 단순 용량에서 '대역폭과 전력효율'로 바뀌었고, LPDDR6는 그 요구에 맞춰 새로 설계된 규격이다. 새 메모리 규격은 칩 혼자 잘 만들어서 끝나지 않는다. 실제로 그 메모리를 품고 돌아갈 AP와 짝을 맞춰 동작 검증을 통과해야 비로소 양산 일정이 확정되고, 이때 가장 먼저 검증을 통과한 회사의 제품이 사실상 업계 표준 물량을 가져간다. 삼성전자가 퀄컴과 함께 그 첫 관문을 통과했다는 것은 내년 이후 출시될 플래그십 AI 스마트폰의 메모리 공급 구도가 이미 한국 쪽으로 기울었다는 뜻이다. 서버용 HBM에서 세계 최초 HBM4 양산 출하를 기록한 데 이어, 모바일 메모리에서도 규격 선점을 이어가는 모습이다.",
   src:"서울신문", url:"https://www.seoul.co.kr/news/economy/industry/2026/09/24/20260924031006",
   yt:3, ytnote:"AI폰의 심장을 누가 먼저 정하나 — LPDDR6 업계 최초 검증의 의미",
   videos:[],
   related:[{t:"삼성전자, 세계 최초 HBM4 양산 출하…\"업계 최고 성능\" (삼성반도체 뉴스룸)", u:"https://semiconductor.samsung.com/kr/news-events/news/samsung-ships-industry-first-commercial-hbm4-with-ultimate-performance-for-ai-computing/"}]},

  {cat:"tech", date:"2026-08-18", econ:true, intl:true, country:"미국·대만", size:"중견", company:"HPSP", wclass:"대체불가", world:"450℃ 이하에서 100% 수소농도를 유지하는 고압 수소 어닐링 장비를 세계에서 유일하게 상용 공급하며, TSMC 2나노 라인을 포함한 글로벌 선단공정 고객이 대체 공급처를 찾지 못하고 있다.", pride:true,
   title:"세계에 이 장비를 만드는 회사가 한 곳뿐이다…HPSP, TSMC 2나노 라인까지 들어간다",
   desc:"반도체 미세공정이 2나노대로 내려오면 트랜지스터와 절연막 사이 '계면'에 생기는 미세 결함이 성능을 깎아먹는다. 이 결함을 치유하는 방법이 고압 수소 어닐링인데, 수소를 100% 농도로 높은 압력까지 밀어넣으면서도 450℃ 이하 저온을 유지해야 한다. 고온을 쓰면 이미 만들어놓은 회로가 망가지고, 수소는 폭발 위험 때문에 고압 인증 자체가 난관이다. 이 조건을 모두 통과해 양산 장비를 팔고 있는 회사는 전 세계에 한국의 HPSP 한 곳뿐이다. 회사는 고압 인증을 획득한 유일한 업체로, 사실상 전 세계 칩 전공정용 고압 수소 어닐링 시스템을 독점 공급하고 있고 최소 5년간 독점이 유지될 것으로 보고 있다. 2026년 하반기에는 TSMC의 2나노(N2P) 양산 라인에 직결되는 차세대 어닐링 장비가 입고될 예정이고, 2025년까지 단일 고객사에 머물던 양산 장비 매출처가 2026년 4개사, 2027년 5개사로 늘어 글로벌 낸드 공급사 전체로 확대될 전망이다. 증권가 추정 2026년 매출은 2300억 원대, 영업이익률은 50%를 넘는다. 장비 한 대가 없으면 라인이 안 돌아가는 위치에 있는 회사만 낼 수 있는 숫자다.",
   src:"머니투데이", url:"https://www.mt.co.kr/stock/2026/08/18/2026081818567086457",
   yt:3, ytnote:"세계에 하나뿐인 장비 — 수소 고압과 450℃ 사이의 좁은 문",
   videos:[],
   related:[{t:"세계 유일 독점 기업 HPSP, 성장 정체의 역설에 빠지다 (리드경제)", u:"https://www.leadeconomy.co.kr/news/articleView.html?idxno=7100"},
            {t:"HPSP :: 반도체 고압수소 어닐링 장비, 독점적 지위 (오렌지보드)", u:"https://orangeboard.co.kr/@good-trader/HPSP-%EB%B0%98%EB%8F%84%EC%B2%B4-%EA%B3%A0%EC%95%95%EC%88%98%EC%86%8C-%EC%96%B4%EB%8B%90%EB%A7%81-%EC%9E%A5%EB%B9%84-%EB%8F%85%EC%A0%90%EC%A0%81-%EC%A7%80%EC%9C%84"}]},

  {cat:"tech", date:"2026-03-04", econ:true, intl:true, country:"미국·싱가포르", size:"중견", company:"한미반도체", wclass:"세계1위", world:"HBM 3D 적층의 필수 장비인 TC 본더 세계 시장 점유율 71.2%로 1위이며, HBM4용 장비는 특정 해외 고객사에 독점 공급한다.", pride:true,
   title:"AI 메모리를 쌓는 기계는 한국에서 나온다…한미반도체 TC본더 세계 점유율 71%",
   desc:"HBM은 D램을 수직으로 쌓아 만든다. 이 '쌓는' 공정을 담당하는 장비가 TC 본더인데, 수십 마이크로미터 두께로 얇게 깎은 칩을 열과 압력으로 붙이면서 수천 개 연결 단자를 하나도 틀리지 않게 맞춰야 한다. 한 층이라도 틀어지면 그 HBM은 폐기다. 그래서 HBM 생산능력은 결국 '쓸 만한 TC 본더를 몇 대 확보했는가'로 결정된다. 한미반도체는 이 장비 글로벌 점유율 71.2%로 세계 1위다. 즉 전 세계 AI 가속기에 들어가는 HBM 대부분이 한국 중견기업이 만든 장비를 거쳐 나온다는 뜻이다. HBM4 세대에서도 양산 장비 테스트를 통과한 곳은 한미반도체와 해외 업체 ASMPT 둘뿐이고, 회사는 특정 해외 고객사에 HBM4 생산 장비를 독점 공급할 것이라고 밝혔다. 2025년 7월부터 HBM4용 'TC 본더 4' 대량생산 체제를 갖췄고, 2026년 하반기에는 차세대 HBM5·HBM6를 겨냥한 '와이드 TC 본더'를 내놓을 계획이다. 엔비디아와 메모리 3사가 HBM을 두고 다투는 동안, 그 모두에게 장비를 파는 자리를 한국 기업이 잡고 있다.",
   src:"뉴스웨이", url:"https://www.newsway.co.kr/news/view?ud=2026030415023165910",
   yt:4, ytnote:"HBM을 쌓는 기계 — 점유율 71%가 만들어지는 마이크로미터의 세계",
   videos:[{t:"삼성과 맞서고 세계 1등 찍은 '한미반도체' / 소비더머니", u:"https://www.youtube.com/watch?v=rS5q2rCF1RQ"},
           {t:"한미반도체, 올해 HBM TC본더 '압도적 1위' 공식화! AI 반도체 '골든 타임' 잡았다!", u:"https://www.youtube.com/watch?v=pr1x_uy31zQ"},
           {t:"한미반도체, TC본더 왕좌 끝내 증명… 영업이익률 50% 벽마저 뚫었다", u:"https://www.youtube.com/watch?v=Mzwz3BniK2A"}],
   related:[{t:"한미반도체 \"HBM4용 TC 본더도 전량 수주할 것\" (한국경제)", u:"https://www.hankyung.com/article/202507301782i"},
            {t:"HBM4 앞두고 엇갈린 성적표…한화·한미 TC본더 경쟁 격화 (데이터뉴스)", u:"https://www.datanews.co.kr/news/article.html?no=143548"}]},

  {cat:"tech", date:"2026-09-06", econ:true, intl:true, country:"미국·유럽·중국", size:"중견", company:"K바이오 업계", wclass:"해외인정", world:"올해 들어 국내 제약·바이오 기업이 글로벌 빅파마와 맺은 기술수출 계약 규모가 21조 원을 넘겼고, 상반기만 13조 원으로 빅파마가 한국을 '글로벌 주요 파트너'로 취급하기 시작했다.", pride:true,
   title:"빅파마가 한국에 줄을 섰다…올해 기술수출만 21조 원, K바이오 새 기준선",
   desc:"신약 기술수출은 발표 때 금액이 커 보여도 실제로는 대부분 후보물질 단계의 '가능성'을 파는 거래다. 그래서 진짜 지표는 총액이 아니라 계약금(선급금)과 지분 투자 여부다. 돈을 미리 얹는다는 건 사는 쪽이 데이터를 믿는다는 뜻이기 때문이다. 2026년 국내 제약·바이오 업계의 기술수출 누적 규모는 21조 원을 넘겼고, 상반기만 주요 계약 8건에 13조 원을 기록했다. 달라진 것은 구조다. 선급금이 수천억 원대로 올라오고, 빅파마가 기술을 사는 데 그치지 않고 한국 기업 지분까지 함께 취득하는 거래가 등장했다. 거래 품목도 희귀질환 일부에 몰려 있던 과거와 달리, 비만·알츠하이머 같은 만성질환 대형 시장으로 넓어졌다. 글로벌 제약사들이 자체 파이프라인의 빈칸을 메울 때 한국 바이오텍을 1순위 탐색 대상으로 본다는 신호다. 20조 원대가 예외적 대박이 아니라 새로운 기준선으로 자리 잡는 국면이다.",
   src:"머니투데이 더바이오", url:"https://www.mt.co.kr/thebio/2026/09/06/2026090613244280629",
   yt:3, ytnote:"총액보다 선급금을 봐라 — 빅파마가 K바이오에 현금을 얹기 시작한 이유",
   videos:[],
   related:[{t:"선급금만 수천억, 빅파마와 지분거래도…K-바이오 달라졌다 (머니투데이)", u:"https://www.mt.co.kr/thebio/2026/06/28/2026062513325250233"},
            {t:"K바이오, 신약 경쟁력 입증… 기술수출, 역대 최대 또 넘본다 (파이낸셜뉴스)", u:"https://www.fnnews.com/news/202608301753135370"}]},

  {cat:"tech", date:"2026-05-14", econ:true, intl:true, country:"중국", size:"중소", company:"아리바이오", wclass:"글로벌수주", world:"경구용 알츠하이머 치료제 AR1001의 글로벌 독점 판권을 중국 푸싱제약에 최대 47억 달러(약 7조 원) 규모로 넘겼다 — 후기 임상 단계의 먹는 치매약을 가진 기업은 세계적으로 손에 꼽힌다.", pride:true,
   title:"먹는 치매약을 가진 회사는 세계에 몇 없다…아리바이오, 7조 원 판권 계약",
   desc:"알츠하이머 치료제 시장에서 현재 허가된 약들은 대부분 주사제이고, 정기적으로 병원에 가서 투여받아야 한다. 환자와 가족이 진짜 원하는 것은 집에서 먹는 알약이다. 그래서 경구용 후보물질을 후기 임상까지 끌고 간 기업은 세계적으로 매우 드물다. 한국 바이오벤처 아리바이오가 중국 푸싱제약과 경구용 알츠하이머 치료제 'AR1001'의 글로벌 독점 판권 계약을 체결했다. 총 규모는 최대 47억 달러, 약 7조 원이다. 임상 개발에 쓰는 옵션 비용 6000만 달러를 먼저 받고, 임상 3상 톱라인 발표 시 8000만 달러를 더해 총 1억4000만 달러(약 2100억 원)를 선급금으로 단계 수령하며, 이후 허가·상업화 마일스톤과 최대 20% 수준의 로열티가 별도로 붙는다. AR1001은 미국·유럽·영국·중국·한국에서 1500명 이상이 참여한 글로벌 임상 3상(POLARIS-AD)을 진행해 막바지 단계에 와 있다. 대기업이 아닌 국내 바이오벤처가 자체 후보물질 하나로 조 단위 글로벌 판권을 팔았다는 점이 이 계약의 무게다.",
   src:"이데일리 팜이데일리", url:"https://pharm.edaily.co.kr/news/read?newsId=03276726645448920",
   yt:3, ytnote:"주사가 아니라 알약 — 7조 원짜리 먹는 치매약의 임상 3상 이야기",
   videos:[],
   related:[{t:"아리바이오 \"푸싱제약과 계약금 2100억 규모 AR1001 판권 계약\" (히트뉴스)", u:"https://www.hitnews.co.kr/news/articleView.html?idxno=76130"},
            {t:"아리바이오, 7조 기술수출 '선급금' 1000만불 조기 수령 (파이낸셜뉴스)", u:"https://www.fnnews.com/news/202605261006139220"}]},

  {cat:"tech", date:"2026-06-09", econ:true, intl:true, country:"글로벌", size:"대기업", company:"HD한국조선해양·한화오션·삼성중공업", wclass:"세계1위", world:"올해 전 세계 가스 운반선(VLGC·VLAC) 발주의 80%를 한국 조선 3사가 가져갔고, 2028년까지 건조 슬롯이 사실상 매진됐다.", pride:true,
   title:"세계가 주문한 가스선 10척 중 8척…한국 조선소 슬롯은 2028년까지 매진",
   desc:"LNG·암모니아 운반선은 '배'보다 '압력용기를 띄운 화학공장'에 가깝다. 영하 163℃ 액화천연가스를 수만 톤 실은 채 몇 주를 항해하면서 기화 손실을 최소로 묶어야 하고, 화물창 단열과 용접 품질이 조금만 흐트러져도 선급 인증을 받지 못한다. 그래서 선주들은 값이 싸다고 조선소를 바꾸지 않는다. 2026년 들어 5월까지 전 세계 가스 운반선(VLGC·VLAC) 발주 물량의 80%가 한국 조선 3사로 갔다. 중국이 컨테이너선·벌크선 물량을 가격으로 흡수하는 동안, 한 척당 수천억 원이 오가는 고부가 가스선 영역은 한국이 사실상 독점 구도를 유지하고 있다는 뜻이다. 결과적으로 국내 빅3의 건조 슬롯은 2028년까지 거의 매진됐고, 업계는 3.5년치 일감을 확보한 상태로 올해를 보내고 있다. 여기에 LNG 생산설비(FLNG)와 방산 함정·미국 MRO 물량이 얹히면서, 한국 조선업은 단순 회복이 아니라 '가장 어려운 배만 골라 받는' 구조로 옮겨가고 있다.",
   src:"한국경제", url:"https://www.hankyung.com/article/2026041362191",
   yt:3, ytnote:"영하 163도를 실어 나르는 배 — 왜 선주들은 한국 조선소만 찾나",
   videos:[],
   related:[{t:"K조선, 가스선·LNG 생산설비 '싹쓸이' (네이트 뉴스)", u:"https://m.news.nate.com/view/20260609n29456"},
            {t:"[점프업 K-조선] 친환경 고부가가치 LNG선 싹쓸이 수주의 비밀 (브릿지경제)", u:"https://www.viva100.com/article/20260114500953"}]},

  {cat:"tech", date:"2026-05-13", econ:false, intl:true, country:"미국·캐나다", size:"중소", company:"연세대 양자정보학과 연구팀", wclass:"세계최초", world:"양자컴퓨터로 AI 학습이라는 실용 문제의 성능을 실제로 개선한 세계 최초 사례로, 정답 후보를 고전 방식보다 64배 빠르게 얻어내 국제학술지 '피지컬 리뷰 E'에 게재됐다.", pride:true,
   title:"AI의 40년 난제를 양자컴퓨터로 풀었다…한국 연구진, 세계 첫 실용 성과",
   desc:"볼츠만 머신은 1980년대에 제안된 생성형 AI의 원형 격 모델이다. 이론적으로 강력하지만, 학습에 필요한 확률 분포에서 표본을 뽑는 계산량이 폭발해 40년간 실용화되지 못했고 결국 딥러닝의 다른 계열에 자리를 내줬다. 연세대 박경덕 교수팀은 이 병목을 양자 어닐러로 우회했다. 양자 어닐러가 원하는 볼츠만 분포에 맞는 표본을 만들도록 제어하고, 거기서 나온 표본으로 볼츠만 머신을 학습시키는 프레임워크를 제시했다. 캐나다 디웨이브의 '어드밴티지2' 양자 어닐러에서 노드 1984개 규모 모델을 돌린 결과, 고전 방식보다 학습 속도와 성능이 모두 개선됐고 정확한 정답 후보를 64배 빠르게 얻었다. 그동안 양자컴퓨터는 '언젠가 쓸모가 있을 기계'로 불렸는데, AI 학습이라는 현실 문제에서 개선을 실증한 첫 연구라는 점에서 의미가 다르다. 논문은 국제학술지 '피지컬 리뷰 E'에 실렸다.",
   src:"YTN", url:"https://www.ytn.co.kr/_ln/0105_202605260224561737",
   yt:3, ytnote:"40년 묵은 AI 모델이 양자컴퓨터로 부활한다 — 64배의 의미",
   videos:[{t:"한국 연구진, AI의 미래를 바꿀 기술 '세계 최초' 성공..한국 양자컴퓨터 기술의 위력 / YTN 사이언스", u:"https://www.youtube.com/watch?v=FAC44lH67Y8"}],
   related:[{t:"연세대, 양자-AI 융합 프레임워크 제시…\"볼츠만 머신 부활 신호\" (테크월드)", u:"https://www.epnc.co.kr/news/articleView.html?idxno=401733"},
            {t:"생성형AI 시초 '볼츠만 머신', 양자컴퓨팅으로 성능 개선 (다음 뉴스)", u:"https://v.daum.net/v/20260513174715461"}]},

  {cat:"tech", date:"2026-08-31", econ:true, intl:true, country:"유럽·일본·미국", size:"스타트업", company:"글루가(ohora)", wclass:"세계최초", world:"디스플레이용 필름 경화 기술을 네일에 옮겨 '60%만 굳힌 반경화 젤'을 세계 최초로 개발·양산했고, 유럽 독점 공급 계약과 일본 누적 매출 1000억 원, 북미 오프라인 5000여 매장 입점으로 이어졌다.", pride:true,
   title:"디스플레이 공정 기술로 손톱을 뒤집었다…'반경화 젤' 세계 최초, 오호라의 수출기",
   desc:"젤네일은 액상 젤을 바르고 UV 램프로 완전히 굳혀야 해서 살롱에 가야 했다. 글루가는 여기서 발상을 바꿨다. 디스플레이용 필름을 부분 경화시키는 공정 기술을 가져와, 액상 젤을 60%만 굳힌 '반경화' 상태의 필름으로 만든 것이다. 손톱에 붙인 뒤 램프로 남은 40%를 굳히면 살롱 젤과 같은 물성이 나온다. 스티커도 아니고 완제품 젤도 아닌 이 중간 상태를 안정적으로 유지하며 양산하는 기술을 세계 최초로 구현했고, 셀프 네일 브랜드 '오호라'로 상품화했다. 성과는 국내에 머물지 않았다. 초기 D2C 중심 모델에서 대형 유통망과 OEM으로 확장하며 유럽 독점 공급 계약을 체결했고, 일본에서는 누적 매출 1000억 원을 넘겼으며 북미에서는 글로벌 이커머스와 대형 오프라인 매장 5000여 곳에 들어갔다. 반도체·디스플레이 공정에서 쌓인 기술이 뷰티 소비재로 건너가 세계 시장을 새로 만든 사례다. 포브스코리아는 이 회사를 '2026 대한민국 고속성장 스타트업 50'에 올렸다.",
   src:"포브스코리아", url:"https://www.forbeskorea.co.kr/news/articleView.html?idxno=402216",
   yt:3, ytnote:"60%만 굳힌다 — 디스플레이 공정이 네일 시장을 삼킨 방법",
   videos:[],
   related:[{t:"ohora official 유튜브 채널", u:"https://www.youtube.com/channel/UCV72a2QWRpEZjZYkWjXHZWQ/videos?view=0"}]},

  {cat:"sports", date:"2026-08-23", econ:false, intl:true, country:"중국", size:"중소", company:"백하나·이소희", wclass:"세계1위", world:"세계배드민턴연맹(BWF) 세계선수권 여자복식 결승에서 세계랭킹 1위 중국 조를 2-0으로 완파해, 31년 만에 이 종목 세계 정상에 올랐다.", pride:true,
   title:"세계 1위 중국을 2-0으로 눌렀다…백하나·이소희, 31년 만의 세계선수권 금",
   desc:"백하나·이소희가 2026 세계배드민턴연맹(BWF) 세계선수권대회 여자복식 결승에서 세계랭킹 1위 중국의 류성수-탄닝 조를 2-0으로 제압하고 우승했다. 한국 여자복식이 세계선수권 정상에 선 것은 1995년 로잔 대회 길영아-장혜옥 조 이후 31년 만이다. 배드민턴 여자복식은 중국이 국가 차원의 두꺼운 선수층으로 오랫동안 지배해온 종목이라, 랭킹 1위 조를 세트 하나 내주지 않고 이기는 일 자체가 드물다. 이 경기에서 나온 156샷 랠리는 두 선수의 체력과 집중력이 어디까지 버티는지를 보여준 장면으로 남았다. 안세영이 단식에서 세계 최상위를 지키는 동안 복식에서도 정상급 조가 나왔다는 것은, 한국 배드민턴이 한 명의 천재에 의존하는 구조를 벗어나고 있다는 신호다.",
   src:"서울신문", url:"https://www.seoul.co.kr/news/sport/badminton/2026/08/23/20260823500095",
   yt:4, ytnote:"156샷 랠리 — 중국 벽을 31년 만에 넘은 여자복식의 경기 해부",
   videos:[{t:"[BWF] 세계선수권대회 여자 복식 결승 류성수&탄닝 vs 백하나&이소희 하이라이트", u:"https://www.youtube.com/watch?v=8sbRh-3cJAI"},
           {t:"31년 만의 기적! 백하나-이소희, 세계 1위 중국을 2-0 완파!", u:"https://www.youtube.com/watch?v=zxcNEhwUhVw"},
           {t:"\"솔직히 힘들었는데 감췄어요\"...이소희-백하나, 지옥의 '156샷 랠리' 뒷이야기", u:"https://www.youtube.com/watch?v=Tain25ywM8w"}],
   related:[{t:"백하나/이소희 vs 류성슈/탄닝 | 2026 말레이시아 오픈 결승전 (유튜브)", u:"https://www.youtube.com/watch?v=Uul51sgGCmo"},
            {t:"체육일정 월간일정 (대한체육회 스포츠지원포털)", u:"https://g1.sports.or.kr/schedule/month.do"}]},

  {cat:"culture", date:"2026-07-05", econ:true, intl:true, country:"미국·중동", size:"대기업", company:"농심·삼양식품 등", wclass:"세계1위", world:"미국 라면 수입시장에서 한국이 점유율 44.1%로 1위이며 2014년 이후 줄곧 최대 수출국 자리를 지켰고, 상반기 K-푸드+ 수출은 70.5억 달러로 역대 최고다.", pride:true,
   title:"미국이 먹는 라면 10개 중 4개는 한국산…상반기 K-푸드 수출 70억 달러 돌파",
   desc:"2026년 상반기 K-푸드+ 수출액이 70억5000만 달러로 역대 최고를 기록했다. 견인차는 라면이다. 상반기 라면 수출액만 9억3539만 달러로 전년 대비 28% 늘었고, 2022년 3억 달러였던 것이 2023년 4억, 2024년 5억, 2025년 7억을 거쳐 올해 9억 달러대로 올라섰다. 연간 첫 20억 달러 돌파가 사정권이다. 주목할 것은 점유율이다. 라면의 본가는 일본이지만, 미국 라면 수입시장에서 한국은 44.1%로 1위이며 2014년 이후 줄곧 최대 수출국 자리를 지켜왔다. 불닭볶음면이 소셜미디어 챌린지로 퍼지고 신라면이 대형 유통망에 자리를 잡으면서, 라면은 교민 상대 식품에서 현지인 일상 식품으로 넘어갔다. 증가율 1위 지역은 중동이었다. 한류 콘텐츠가 만든 호감이 실제 반복 구매로 전환되면 무엇이 되는지를 보여주는 숫자다.",
   src:"파이낸셜뉴스", url:"https://www.fnnews.com/news/202607051100444453",
   yt:3, ytnote:"라면 본가는 일본인데 미국 1위는 한국 — 점유율 44%가 만들어진 과정",
   videos:[],
   related:[{t:"'신라면·불닭' 투톱 내세운 K라면...\"올해 수출 사상 첫 20억달러 도전\" (머니투데이)", u:"https://www.mt.co.kr/living/2026/07/06/2026070614020163512"},
            {t:"상반기 K푸드 수출 '역대 최대'…증가율 1위는 '중동' (아시아경제)", u:"https://view.asiae.co.kr/article/2026070511142143919"}]},

  {cat:"sports", date:"2002-06-22", classic:true, econ:false, intl:false, pride:true, title:"2002 한일월드컵, 스페인 꺾고 아시아 최초 4강…'4강 신화'가 시작된 날",
   desc:"2002년 6월 22일 광주에서 열린 한일월드컵 8강전에서 한국이 스페인과 120분 혈투 끝에 승부차기 5-3으로 승리하며 아시아 국가 최초로 월드컵 4강에 올랐다. 이운재의 선방과 홍명보의 마지막 킥이 역사를 만들었고, 전국 거리에는 수백만 명의 붉은 물결이 쏟아졌다. 1954년 첫 출전 이후 48년 만에 본선 첫 승(폴란드전)을 거둔 대회이기도 하다.",
   src:"Wikipedia", url:"https://en.wikipedia.org/wiki/2002_FIFA_World_Cup",
   yt:5, ytnote:"승부차기 5-3, 그날의 120분을 다시 본다 — 4강 신화 완전 복기",
   videos:[{t:"'4강 신화', 호아킨 막은 이운재와 마무리한 홍명보 | 2002 FIFA 월드컵 8강 대한민국 VS 스페인", u:"https://www.youtube.com/watch?v=6Kr-_veieNw"},
           {t:"[리플레이] 대한민국이 아시아 최초로 월드컵 4강에 진출했던 순간", u:"https://www.youtube.com/watch?v=ibnH3f2UIY8"},
           {t:"\"4강 신화 탄생! 스페인을 승부차기에서 꺾습니다!\" 2002년 한일 월드컵 스페인전 / SBS", u:"https://www.youtube.com/watch?v=I9Owon_gk5E"}],
   related:[{t:"2002 한일월드컵 4강 신화 태극전사 재조명 (한국생활체육뉴스)", u:"http://www.kstnews.co.kr/news/articleView.html?idxno=21138"},
            {t:"[다시보는 2002 월드컵] 한국축구 4강 신화 하이라이트", u:"https://www.youtube.com/watch?v=kdYsF6rbMjs"}]},

  {cat:"culture", date:"2020-02-09", classic:true, econ:false, intl:true, country:"미국", pride:true, title:"'기생충', 아카데미 작품상 수상…92년 역사상 비영어 영화 최초",
   desc:"봉준호 감독의 '기생충'이 2020년 2월 9일(현지시각) 제92회 아카데미 시상식에서 작품상·감독상·각본상·국제장편영화상 4관왕에 올랐다. 비영어권 영화가 아카데미 작품상을 받은 것은 시상식이 시작된 이래 처음이며, 비영어 영화가 작품상과 감독상을 동시에 가져간 것도 사상 최초다. \"1인치 자막의 장벽을 넘으면\"이라는 봉 감독의 수상 소감은 그해 전 세계가 인용한 문장이 됐다.",
   src:"VOA 코리아", url:"https://www.voakorea.com/a/korea_korea-life_academyawards-parasite/6029036.html",
   yt:5, ytnote:"1인치 자막의 장벽 — '기생충'이 오스카 92년의 규칙을 깬 과정 복기",
   videos:[{t:"아카데미 작품상 '기생충' 호명되는 순간… / YTN", u:"https://www.youtube.com/watch?v=zGms9ShsjjA"},
           {t:"[제92회 아카데미] \"92년 오스카 벽 부쉈다!\"…'기생충' 작품상 수상 외신 반응은? / KBS", u:"https://www.youtube.com/watch?v=5tV-B8zJ6Y8"},
           {t:"'기생충' 작품상까지 4관왕…아카데미 92년 역사 깼다 | 뉴스A", u:"https://www.youtube.com/watch?v=aZKljkRE38w"}],
   related:[{t:"<기생충> 제92회 아카데미 시상식 4관왕, 2020 아카데미 최다 수상 (CJ 뉴스룸)", u:"https://cjnews.cj.net/%EA%B8%B0%EC%83%9D%EC%B6%A9-%EC%A0%9C92%ED%9A%8C-%EC%95%84%EC%B9%B4%EB%8D%B0%EB%AF%B8-%EC%8B%9C%EC%83%81%EC%8B%9D-%EC%9E%91%ED%92%88%EC%83%81-%EA%B0%90%EB%8F%85%EC%83%81-%EA%B0%81%EB%B3%B8/"},
            {t:"美 연예 매체 \"기생충, 역대 최고의 오스카 작품상 수상작\" / YTN", u:"https://www.youtube.com/watch?v=9JflQ6MW0ZE"}]},

  {cat:"sports", date:"2010-02-26", classic:true, econ:false, intl:false, pride:true, title:"김연아, 밴쿠버 올림픽 피겨 금메달…총점 228.56 세계신기록으로 아시아 벽을 깼다",
   desc:"2010년 2월 26일 밴쿠버 동계올림픽 피겨스케이팅 여자 싱글에서 김연아가 프리 150.06점, 총점 228.56점이라는 세계 최고기록으로 금메달을 차지했다. 한국인 최초의 올림픽 피겨 금메달이자, 쇼트·프리·총점 세계기록을 한 대회에서 모두 갈아치운 기록이었다. 2위와의 점수 차는 23점이 넘었고, 거슈윈 피아노 협주곡에 맞춘 그 연기는 지금도 피겨 역사상 최고의 프로그램으로 꼽힌다.",
   src:"VOA 코리아", url:"https://www.voakorea.com/a/a-35-2010-02-26-voa6-91416569/1329877.html",
   yt:5, ytnote:"228.56 — 16년이 지나도 회자되는 4분간의 완벽, 점수표로 뜯어보기",
   videos:[{t:"\"김연아! 피겨 여왕의 시대가 열립니다!\" 2010 밴쿠버 김연아 금메달 연기 (풀영상) / SBS", u:"https://www.youtube.com/watch?v=2DEDNW5Jq4Q"},
           {t:"김연아, 환상적인 연기로 세계 신기록을 달성했던 역사적인 순간｜2010 밴쿠버 프리프로그램", u:"https://www.youtube.com/watch?v=SJqdiEHs-xE"},
           {t:"[올림픽 공식] 김연아가 말하는 2010 밴쿠버 동계올림픽 금메달의 순간", u:"https://www.youtube.com/watch?v=R8Z97TLObnk"}],
   related:[{t:"Kim Yu-na, Women's Singles Figure Skating | Vancouver 2010 (Olympics.com)", u:"https://www.olympics.com/en/video/kim-yu-na-women-s-singles-figure-skating-vancouver-2010"},
            {t:"[오마이뉴스 선정 21세기 100대 뉴스] 김연아 밴쿠버 여자 피겨 금메달", u:"https://www.ohmynews.com/NWS_Web/Event/20th/at_pg.aspx?CNTN_CD=A0002612674"}]},

  {cat:"culture", date:"2022-09-12", classic:true, econ:false, intl:true, country:"미국", pride:true, title:"'오징어 게임', 에미상 감독상·남우주연상 수상…74년 역사상 비영어 드라마 최초",
   desc:"2022년 9월 12일(현지시각) 제74회 프라임타임 에미상에서 넷플릭스 '오징어 게임'의 황동혁 감독이 드라마 시리즈 감독상을, 이정재가 남우주연상을 받았다. 비영어권 드라마가 에미상 감독상과 남우주연상을 수상한 것은 74년 역사상 처음이며, 작품상 후보에 오른 것도 비영어 드라마로는 최초였다. 이정재는 한국어로 수상 소감을 남기며 국내 시청자들과 기쁨을 나눴다.",
   src:"MBC 뉴스", url:"https://imnews.imbc.com/replay/2022/nw1200/article/6407256_35715.html",
   yt:5, ytnote:"자막의 벽을 두 번째로 무너뜨린 밤 — '오징어 게임'이 에미상에서 바꾼 규칙",
   videos:[{t:"'오징어 게임' 에미상서 이정재 남우주연상, 황동혁 감독상 수상 / KBS 2022.09.13.", u:"https://www.youtube.com/watch?v=CpRcvHlfWV8"},
           {t:"에미상 휩쓴 '오징어 게임'‥비영어권 최초 (2022.09.14/뉴스투데이/MBC)", u:"https://www.youtube.com/watch?v=6z-dPWLnLmI"},
           {t:"'오징어게임' 이정재·황동혁 센스 만점 수상 소감 (현장영상) / SBS", u:"https://www.youtube.com/watch?v=qSbCd_5LqYg"}],
   related:[{t:"'오징어게임', 비영어 드라마 최초 에미상 작품상 후보 (경향신문)", u:"https://www.khan.co.kr/article/202207130751001"},
            {t:"'오징어 게임' 미국 에미상 감독상·남우주연상 수상…비영어권 최초 / KBS", u:"https://www.youtube.com/watch?v=USsIy6EjGMQ"}]},

  // ── 국제기여 아카이브: 한국이 다른 나라를 도운 이야기 ──
  {cat:"culture", date:"1999-10-04", classic:true, aid:true, country:"동티모르", econ:false, intl:true, pride:true,
   title:"동티모르 상록수부대…구스마오 대통령이 취임 후 가장 먼저 찾은 나라가 한국이었다",
   desc:"1999년 10월 파병된 상록수부대는 동티모르 13개 군 가운데 로스팔로스와 오쿠시 2개 군에 각각 2년씩 주둔하며 4년간 지역 안정화를 이끌었다. 파견국 중 유일하게 대민지원 작전 '블루엔젤'을 별도로 전개해 동티모르 정부와 유엔군사령부로부터 '가장 모범적인 부대'라는 평가를 받았다. 임무 수행 중 순직한 부대원 5명의 추모식은 지금도 현지 오에쿠시에서 열린다.",
   legacy:"2002년 6월 취임한 구스마오 대통령은 외국 가운데 한국을 가장 먼저 방문해 파병에 사의를 표했고, 상록수부대가 주둔했던 지역 주민들을 \"동티모르인 가운데 가장 복 받은 주민\"이라고 표현했다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/policyNewsView.do?newsId=50002709",
   yt:5, ytnote:"한 나라의 대통령이 취임 후 첫 외국 방문지로 한국을 고른 이유 — 상록수부대 4년의 기록",
   videos:[{t:"[영상] 육군 상록수부대 동티모르 파병 (1999.10.04)", u:"https://www.youtube.com/watch?v=YQL3LyKkBZQ"},
           {t:"한국군 최초 PKO 상록수 부대 | 소말리아인이 놀란 상록수 부대", u:"https://www.youtube.com/watch?v=ZHQcd46Je_A"},
           {t:"동티모르 상록수부대 순직 15주기 추모식 열려 / YTN KOREAN", u:"https://www.youtube.com/watch?v=UCXMSncc8eA"}],
   related:[{t:"상록수부대(常綠樹部隊) — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0068134"},
            {t:"상록수부대 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%83%81%EB%A1%9D%EC%88%98%EB%B6%80%EB%8C%80"}]},

  {cat:"culture", date:"2007-07-19", classic:true, aid:true, country:"레바논", econ:false, intl:true, pride:true,
   title:"레바논 동명부대 18년…남부 티르 주민들이 부르는 이름은 '신이 준 선물'",
   desc:"2007년 6월 창설돼 7월 레바논 남부 티르 지역에 전개된 동명부대는 국군 해외파병 부대 가운데 최장수 부대다. UNIFIL 서부여단 소속으로 정전 감시와 폭발물 제거를 맡는 동시에, 의료지원과 학교·공공시설 개보수, 주민 일자리 창출형 민사작전을 이어왔다. 이스라엘-헤즈볼라 충돌이 반복되는 최전선에서 18년째 자리를 지키고 있다.",
   legacy:"현지 주민들은 동명부대를 '신이 준 선물'이라 부르며, 부대의 민군작전은 레바논 남부 안정화에 크게 기여한 것으로 평가받는다. 부대가 운영한 태권도 교실 출신 '레바논 태권도 키즈'는 지역의 상징이 됐다.",
   src:"한국민족문화대백과사전", url:"https://encykorea.aks.ac.kr/Article/E0080634",
   yt:4, ytnote:"18년을 한 도시에 머문 군대 — 티르 아이들이 한국어로 태권도 구령을 외치기까지",
   videos:[{t:"폭발물 제거, 의료 지원, 태권도 지도까지…레바논 티르의 동명부대 (KBS 2016.10.01)", u:"https://www.youtube.com/watch?v=r_-EVatiKPQ"},
           {t:"피쓰 투 레바논 — 국제평화를 지키는 그들의 이야기 #동명부대 #UNIFIL", u:"https://www.youtube.com/watch?v=7U01CCkV_T0"},
           {t:"레바논의 푸른 희망 동명부대 2부 [강군365 200회]", u:"https://www.youtube.com/watch?v=EXq55Sup3l4"}],
   related:[{t:"대한민국 레바논 평화 유지단 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EB%A0%88%EB%B0%94%EB%85%BC_%ED%8F%89%ED%99%94_%EC%9C%A0%EC%A7%80%EB%8B%A8"},
            {t:"내가 바로 레바논 태권도 키즈 #동명부대", u:"https://www.youtube.com/shorts/BuHdSrXD8TI"}]},

  {cat:"culture", date:"2013-04-01", classic:true, aid:true, country:"남수단", econ:false, intl:true, pride:true,
   title:"남수단 한빛부대, 307km '생명의 도로'…피보르 시장 \"남수단이 번영한 건 한빛부대 덕\"",
   desc:"2013년 남수단 종글레이주 보르에 전개된 한빛부대는 UNMISS 소속으로 12년 넘게 재건지원 임무를 이어오고 있다. 보르~피보르~아코보를 잇는 307km 주보급로를 보수해 현지 물류의 생명줄을 만들었고, 2014년에는 보르시에 르왈딧 초등학교를 세웠다. 한빛직업학교와 한빛농장으로 기술을 전수하고 한국어·태권도 교실도 운영한다.",
   legacy:"피보르 시장 보요이 골라는 \"남수단이 번영하고 무역이 활성화된 것은 한빛부대가 수백km 도로를 건설한 재건 작전 덕분\"이라 말했고, 구무룩 마을 위원장은 \"아이들과 여성, 노인 모두가 나아진 도로를 보고 행복해했다\"고 감사를 전했다. 현지에서 한빛부대의 별명은 '신이 내린 선물'이다.",
   src:"세계일보", url:"https://www.segye.com/newsView/20250330507167",
   yt:5, ytnote:"307km 흙길이 나라의 무역로가 되기까지 — 남수단이 한국군을 '신이 내린 선물'이라 부르는 이유",
   videos:[{t:"남수단 신이 내린 선물｜한빛부대 파병 10주년을 기하며", u:"https://www.youtube.com/watch?v=krCCOx5po3s"},
           {t:"[한빛부대 16진] 남수단 주민에 '생명의 도로' 선물", u:"https://www.youtube.com/watch?v=c0dgHNY7hxs"},
           {t:"\"신이 내린 선물\"…국군의 날 기념 해외파병부대(청해·아크·한빛·동명) 활약상 공개", u:"https://www.youtube.com/watch?v=y8IXVo2WMDQ"}],
   related:[{t:"남수단 국민은 왜 한빛부대를 \"신이 내린 선물\"이라 찬사 보낼까 (문화일보)", u:"https://news.nate.com/view/20250330n04489"},
            {t:"남수단 한빛부대 — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0080633"}]},

  {cat:"culture", date:"2010-03-08", classic:true, aid:true, country:"아이티", econ:false, intl:true, pride:true,
   title:"아이티 단비부대, 철수하며 110억원짜리 주둔지를 통째로 아이티에 넘겼다",
   desc:"2010년 1월 대지진 직후 창설된 단비부대는 3월 8일 레오간에 도착해 2년 9개월간 잔해 제거, 도로 복구, 하천 정비, 우물 개발을 수행했다. 공식 임무가 아니었는데도 난민들에게 우물을 파주고 마을과 학교를 지었으며, 콜레라 방역과 난민촌 진료를 병행했다. 2012년 12월 철수하면서 110억원 규모의 주둔지 시설물 전부를 아이티 정부에 무상 공여하고 떠났다.",
   legacy:"부대가 세운 초등학교와 우물, 그리고 통째로 남기고 간 주둔지 시설은 지금도 레오간에서 사용되고 있다 — 한국군이 '단비'라는 이름 그대로 기억되는 이유다.",
   src:"YTN", url:"https://m.ytn.co.kr/news_view.amp.php?param=0101_201212241602370439",
   yt:3, ytnote:"떠나면서 기지를 통째로 주고 온 부대 — 아이티 '단비'의 2년 9개월",
   videos:[],
   related:[{t:"대한민국 아이티 재건지원단 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EC%95%84%EC%9D%B4%ED%8B%B0_%EC%9E%AC%EA%B1%B4%EC%A7%80%EC%9B%90%EB%8B%A8"},
            {t:"아이티 단비부대, 즐겁고 훈훈한 태권도 현장", u:"https://www.youtube.com/watch?v=_HdWrVphUSM"}]},

  {cat:"culture", date:"2011-01-21", classic:true, aid:true, country:"미얀마·인도네시아", econ:false, intl:true, pride:true,
   title:"아덴만 여명작전…구출된 인질 21명 중 13명은 미얀마·인도네시아 선원이었다",
   desc:"2011년 1월 15일 소말리아 해적에 피랍된 삼호주얼리호를 구하기 위해 청해부대가 작전에 들어가, 피랍 6일 만인 1월 21일 해군특수전전단(UDT/SEAL)이 선박을 급습했다. 해적 8명을 사살하고 5명을 생포하며 인질 21명 전원을 무사히 구출했는데, 이 가운데 미얀마인 11명과 인도네시아인 2명 등 13명이 외국인 선원이었다. 미국·오만·파키스탄 등 다국적 함정이 작전을 지원했다.",
   legacy:"한국 해군이 자국민뿐 아니라 동남아 선원 13명의 목숨까지 함께 구해낸 이 작전은 해양 안보·인도주의 군사작전의 모범 사례로 국제 사회에서 거론된다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/policyNewsView.do?newsId=148726097",
   yt:5, ytnote:"구출된 21명 중 13명은 한국인이 아니었다 — 아덴만 여명작전을 다시 보는 관점",
   videos:[{t:"[국방부] 다큐멘터리 — 아덴만 여명작전 7일간의 기록", u:"https://www.youtube.com/watch?v=ywyBl1KaICw"},
           {t:"삼호주얼리호에 피랍된 21명의 선원들을 구하라! #벌거벗은세계사 EP.31 | tvN", u:"https://www.youtube.com/watch?v=AEjuA2zIPdY"},
           {t:"청해부대 아덴만 여명작전 영상 (S. Korean Navy Rescued Hostages from Somalia Pirates)", u:"https://www.youtube.com/watch?v=VrfvHWUCr_0"}],
   related:[{t:"아덴만 여명 작전 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%95%84%EB%8D%B4%EB%A7%8C_%EC%97%AC%EB%AA%85_%EC%9E%91%EC%A0%84"},
            {t:"소말리아 해역 청해부대 — 한국민족문화대백과사전", u:"https://encykorea.aks.ac.kr/Article/E0080635"}]},

  {cat:"culture", date:"2023-02-08", classic:true, aid:true, country:"튀르키예", econ:false, intl:true, pride:true,
   title:"튀르키예 대지진, 한국 긴급구호대 118명…6·25 때 우리를 도운 그 땅에서 생존자를 꺼냈다",
   desc:"2023년 2월 6일 대지진 직후 외교부·국방부·소방청·KOICA로 구성된 해외긴급구호대(KDRT) 118명이 파견돼 2월 8일 오전 가지안테프 공항에 도착했다. 튀르키예 정부 요청에 따라 하타이주 안타키아를 중점 구조지역으로 선정했고, 2월 9일 구조 개시 90분 만에 첫 생존자를 구해낸 뒤 7시간 만에 5명을 구조했다. 구호대는 3진까지 이어져 3월까지 구조·재건 활동을 계속했다.",
   legacy:"튀르키예는 6·25 때 미국 다음으로 많은 병력을 보낸 '형제의 나라'이며, 한국 구호대가 활동한 지역은 당시 튀르키예군이 한국으로 떠났던 이스켄데룬 인근이었다 — 72년 만에 같은 항구에서 방향만 바뀐 셈이다.",
   src:"외교부", url:"https://www.mofa.go.kr/www/brd/m_4076/view.do?seq=369765",
   yt:5, ytnote:"72년 전 그 항구에서 — 형제의 나라에 진 빚을 갚으러 간 118명",
   videos:[{t:"한국 긴급 구호대, 튀르키예 지진 현장서 생존자 첫 구조", u:"https://www.youtube.com/watch?v=56RwgfnlCkk"},
           {t:"\"튀르키예, 형제의 나라\"…긴급구호대 110명 급파 | 뉴스A", u:"https://www.youtube.com/watch?v=uJOXF9bv4aE"},
           {t:"총 8명의 생존자를 구조하다! 튀르키예·시리아 대지진에서 활약한 대한민국 긴급구호대", u:"https://www.youtube.com/watch?v=KfVzVure7aM"}],
   related:[{t:"정부 긴급구호대 튀르키예 지진 현장 도착해 수색·구조활동 개시 (경향신문)", u:"https://m.khan.co.kr/politics/defense-diplomacy/article/202302081620001"},
            {t:"튀르키예 지진 피해 지원 대한민국 해외긴급구호대(KDRT) 3진 복귀 (외교부)", u:"https://www.mofa.go.kr/www/brd/m_4080/view.do?seq=373500"}]},

  {cat:"culture", date:"2013-12-09", classic:true, aid:true, country:"필리핀", econ:false, intl:true, pride:true,
   title:"태풍 하이옌 폐허의 필리핀에 520명 아라우부대…아키노 대통령이 한국말로 \"감사합니다\"",
   desc:"2013년 11월 슈퍼태풍 하이옌으로 초토화된 필리핀 타클로반에 12월 9일부터 520여 명 규모의 아라우부대가 전개됐다. 전차상륙함 2척에 중형굴삭기 등 19종 30대의 장비와 12종 35t의 물자를 싣고 들어가 잔해 제거와 학교·공공시설 재건, 의료 진료를 수행했으며 2014년 12월 임무를 마쳤다. 부대명 '아라우(Araw)'는 현지어로 태양·희망을 뜻한다.",
   legacy:"베니그노 아키노 필리핀 대통령은 태풍 피해 현장 첫 방문지로 아라우부대가 복구·완공한 타나완 센트럴초등학교를 골랐고, 부대장에게 한국말로 \"감사합니다\"라고 인사했다.",
   src:"대한민국 정책브리핑", url:"https://www.korea.kr/news/interviewView.do?newsId=148774692",
   yt:3, ytnote:"대통령이 피해 현장 첫 방문지로 '한국군이 지은 학교'를 고른 날",
   videos:[],
   related:[{t:"아라우 부대 — 위키백과", u:"https://ko.wikipedia.org/wiki/%EC%95%84%EB%9D%BC%EC%9A%B0_%EB%B6%80%EB%8C%80"},
            {t:"평화유지·사회 재건…현지서 사랑받는 파병 장병들 / YTN", u:"https://www.youtube.com/watch?v=yXfRHL_huRk"}]},

  {cat:"culture", date:"2009-11-25", classic:true, aid:true, country:"OECD 개발원조위원회", econ:true, intl:true, pride:true,
   title:"한국, OECD DAC 24번째 회원국 가입…원조 받던 나라가 주는 나라가 된 세계 유일 사례",
   desc:"2009년 11월 25일 파리 OECD 본부에서 열린 개발원조위원회(DAC) 가입 심사 특별회의에서 회원국 전원 합의로 한국의 가입이 확정됐고, 2010년 1월 1일부터 24번째 정식 회원국으로 활동을 시작했다. 1961년 DAC 출범 이후 원조 수혜국에서 공여국으로 전환한 나라는 한국이 처음이자 유일하다. DAC 회원국들은 한국의 경험이 위원회에 새로운 활력이 될 것이라고 평가했다.",
   legacy:"이후 한국의 개발 경험은 아프리카·동남아 개도국이 직접 배우러 오는 커리큘럼이 됐고, '수원국에서 공여국으로'는 국제개발협력 현장에서 한국을 설명하는 고유명사가 됐다.",
   src:"외교부", url:"https://www.mofa.go.kr/www/brd/m_4080/view.do?seq=325276",
   yt:4, ytnote:"세계 어느 나라도 못 한 방향 전환 — 받던 나라에서 주는 나라로, 1961년 이후 유일",
   videos:[{t:"[개발협력주간] OECD DAC 가입 10주년 기념 SBS 일요특선 다큐멘터리 요약본", u:"https://www.youtube.com/watch?v=wSH8TEkByDw"},
           {t:"수원국에서 공여국이 된 세계 최초, 유일 국가 대한민국 [이슈 픽 쌤과 함께] | KBS", u:"https://www.youtube.com/watch?v=YofyNeUDmqk"},
           {t:"[국민리포트] 원조받던 한국.. 이제 원조하는 나라로!", u:"https://www.youtube.com/watch?v=NryuS0TQWRw"}],
   related:[{t:"선진공여국으로 우뚝 서다, OECD DAC 가입 (외교부 뉴포커스)", u:"https://www.mofa.go.kr/www/brd/m_4076/view.do?seq=325309"},
            {t:"한국, OECD DAC 가입 '선진국 대열 합류' (오마이뉴스)", u:"https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0001269063"}]},

  {cat:"culture", date:"2024-03-22", classic:true, aid:true, country:"에티오피아", econ:false, intl:true, pride:true,
   title:"6·25 참전 에티오피아 강뉴부대…70여 년 뒤 한국이 그 후손들을 찾아간다",
   desc:"1951년 하일레 셀라시에 황제는 황실근위대 6037명을 파병했고, 유엔군 강뉴부대로 253차례 전투에서 모두 승리했다. 그러나 귀국 후 정권이 바뀌며 참전용사들은 '한국을 도왔다'는 이유로 핍박받고 극빈층으로 밀려났다. 사단법인 따뜻한하루는 2016년부터 매년 이들의 가정을 찾아 생계비와 주거환경 개선을 지원하고, 2018년에는 후손들로 '강뉴합창단'을 창단해 장학사업을 이어오고 있다.",
   legacy:"현지에서 참전용사를 돕는 한국인은 '짜이(형제)'로 불리며, 강뉴합창단 후손들은 초청을 받아 한국을 찾아 임진각과 춘천 에티오피아 참전기념탑을 방문한다.",
   src:"한국일보", url:"https://www.hankookilbo.com/News/Read/A2024032210520005705",
   yt:5, ytnote:"한국을 도왔다는 이유로 가난해진 사람들 — 강뉴부대 후손을 찾아가는 보은 프로젝트",
   videos:[{t:"[호국보훈의 달 특집 다큐] 강뉴, 승리의 이름으로 — 에티오피아 참전용사들의 마지막 이야기", u:"https://www.youtube.com/watch?v=B3qNU6DrAdM"},
           {t:"\"할아버지가 구한 나라, 손녀를 구하다\"…해외 참전용사 손녀 수술 지원 / KBS", u:"https://www.youtube.com/watch?v=0FAjPMcWsk0"},
           {t:"한국을 도왔다는 이유로 핍박받은 에티오피아 참전용사들", u:"https://www.youtube.com/watch?v=3cUciXW4074"}],
   related:[{t:"\"참전용사 돕는 한국인은 '짜이'\"… 에티오피아에 퍼진 韓 온기 (국민일보)", u:"https://v.daum.net/v/WLX26shDYD"},
            {t:"LG, 6·25 에티오피아 참전용사 후손 '강뉴합창단' 방한 체류비 후원 (이데일리)", u:"https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=01262806645484016"}]},

  {cat:"culture", date:"2026-06-25", classic:true, aid:true, country:"콜롬비아", econ:false, intl:true, pride:true,
   title:"중남미 유일 6·25 파병국 콜롬비아…한국 대사관이 노병들을 직접 찾아간다",
   desc:"콜롬비아는 6·25 전쟁 당시 중남미에서 유일하게 지상군을 보낸 나라로, 현재 생존 참전용사는 380여 명으로 알려져 있다. 주콜롬비아 한국대사관은 6·25 발발 76주년을 맞아 수도 보고타를 벗어난 부카라망가 지역까지 '찾아가는 보훈 행사'를 열었다. 거동이 어려워 수도 행사에 오지 못하는 고령의 노병들을 한국 정부가 직접 찾아가는 방식이다.",
   legacy:"보고타에서 열린 기념식에는 참전용사 35명과 가족 등 120명이 참석해 '대한민국 국민 보은 메달'을 받았고, 콜롬비아 현지에서는 이들을 '잊혀진 영웅들'로 다시 조명하는 행사가 해마다 이어지고 있다.",
   src:"뉴스토마토", url:"http://www.newstomato.com/ReadNews.aspx?no=1305391",
   yt:3, ytnote:"수도에 못 오는 노병에게 한국이 찾아간다 — 중남미 유일 파병국 콜롬비아 보훈 현장",
   videos:[],
   related:[{t:"\"중남미 유일 파병국 콜롬비아, 한국전 참전 헌신 재조명\" (GOODTV)", u:"https://news.goodtv.co.kr/news/articleView.html?idxno=23923"},
            {t:"콜롬비아에서 대한민국 국민 보은 메달 헌정식 열려 (뉴스코리아)", u:"https://www.newskorea.ne.kr/news/articleView.html?idxno=12137"}]},

  {cat:"culture", date:"2011-01-31", classic:true, aid:true, country:"탄자니아·르완다 등", econ:false, intl:true, pride:true,
   title:"새마을운동, 74개국으로 수출…아프리카 오지 마을이 카사바 의존에서 벗어났다",
   desc:"한국의 1970년대 농촌개발 모델인 새마을운동이 개발 협력 프로그램으로 재설계돼 아프리카·아시아 저개발국에 전파됐다. 탄자니아 운지아냐 마을에서는 마을 지도자가 한국에서 새마을 교육을 받고 돌아온 뒤 주민들이 카사바 뿌리 의존에서 벗어나기 시작했고, 탄자니아 정부는 팡가니 지역에 새마을 방식 마을 조성 계획을 세웠다. 2015년에는 우간다·케냐·에티오피아·세네갈·말라위 등 아프리카 6개국 지역개발 전문가들이 영남대에서 새마을운동을 집중 학습했다.",
   legacy:"르완다는 새마을운동을 국가 농촌개발 모델로 벤치마킹했고, 아프리카 각국 공무원들이 지금도 한국에 연수를 오며 '새마을(Saemaul)'은 번역 없이 그대로 쓰이는 개발협력 용어가 됐다.",
   src:"세계일보", url:"https://www.segye.com/newsView/20110131001473",
   yt:4, ytnote:"'새마을'이 번역 없이 수출된 단어가 된 이유 — 르완다·탄자니아 현장 비교",
   videos:[{t:"한국의 새마을 운동을 도입해 대박난 르완다 마을 방문기 【아프리카6】", u:"https://www.youtube.com/watch?v=OkGSeDPzXyQ"},
           {t:"저개발국에 뿌리내린 '새마을운동' / YTN", u:"https://www.youtube.com/watch?v=26MeK2N0VQU"},
           {t:"기근에 시달리던 르완다가 한국 쌀 심었더니 벌어진 일 | 새마을운동 벤치마킹 #골라듄다큐", u:"https://www.youtube.com/watch?v=3cxfJBZVscs"}],
   related:[{t:"[전국] \"아프리카에 새마을운동을 전해주세요\" / YTN", u:"https://www.ytn.co.kr/_ln/0115_201511270142360461"},
            {t:"아프리카 6개국 지역개발 전문가, 영남대서 '새마을운동' 집중 학습 (영남대 국제개발협력원)", u:"https://www.yu.ac.kr/iidc/board/news.do?mode=view&articleNo=1221711"}]},

  {cat:"culture", date:"2026-06-16", classic:true, aid:true, country:"우간다·케냐·세네갈 등", econ:false, intl:true, pride:true,
   title:"K-벼재배기술이 연 아프리카 녹색혁명…우간다 벼 수확량 2배, 농가 소득 132%↑",
   desc:"농촌진흥청 KOPIA 우간다센터는 2013년 현지 국립농업연구청(NARO)과 함께 설립된 뒤 14개 협력 과제를 수행하고 농업전문가 22명을 파견해 현지 농업인 8666명을 교육했다. 시장가가 높은 향미벼 품종에 한국식 손이앙 기술과 공동재배 방식을 접목한 결과 벼 수확량은 2배 이상, 농가 소득은 132% 늘었다. KAFACI '아프리카 벼개발 파트너십'은 10년간 아프리카 15개국에 71개 벼품종을 개발·등록하고 23개국에서 벼 육종가 44명을 길러냈다.",
   legacy:"세네갈·감비아·기니·가나·카메룬·우간다·케냐 7개국에 'K-라이스벨트' 종자생산단지가 들어서면서, 한국이 만든 벼 품종이 아프리카 농민의 논에서 자국 이름으로 등록돼 재배되고 있다.",
   src:"농촌진흥청", url:"https://rda.go.kr/board/board.do?boardId=farmprmninfo&dataNo=100000811146&mode=updateCnt&prgId=day_farmprmninfoEntry",
   yt:3, ytnote:"한국이 만든 벼가 아프리카 이름으로 등록된다 — 수확량 2배의 기술 이전 구조",
   videos:[],
   related:[{t:"K농업 심은 우간다의 기적…벼 소득 132%·오렌지 소득 309%↑ (헤럴드경제)", u:"https://biz.heraldcorp.com/article/10814419"},
            {t:"K-벼 재배기술, 아프리카에 뿌리 내린다 (한국농어민신문)", u:"https://www.agrinet.co.kr/news/articleView.html?idxno=404902"}]},

  {cat:"culture", date:"2017-06-21", classic:true, aid:true, country:"에콰도르·탄자니아·카메룬 등", econ:true, intl:true, pride:true,
   title:"전자통관시스템 '유니패스' 수출…한국 행정 시스템이 개도국 세관을 바꿨다",
   desc:"관세청의 전자통관시스템 UNI-PASS는 2005년 카자흐스탄을 시작으로 에콰도르·탄자니아·카메룬 등 11개국에 3억4885만 달러 규모로 수출됐다. 특히 에콰도르 사업은 한국의 원조 자금이 아니라 상대국 자체 예산 2400만 달러로 체결돼, 원조가 아닌 실력으로 팔린 첫 사례로 평가된다. 수출입통관·징수·화물관리·관세환급·위험관리를 아우르는 관세행정 전 과정을 통째로 이식한다.",
   legacy:"도미니카공화국·과테말라·탄자니아 등 도입국 세관은 통관 시간이 줄고 부패 여지가 축소됐다고 평가했고, UNI-PASS는 개도국 세관 공무원이 한국으로 연수를 오는 '행정 한류'의 대표 품목이 됐다.",
   src:"한국일보", url:"https://www.hankookilbo.com/News/Read/201706211019855609",
   yt:3, ytnote:"원조가 아니라 제값 받고 판 행정 시스템 — 유니패스가 개도국 세관을 바꾼 방식",
   videos:[],
   related:[{t:"관세청, 에콰도르에 전자통관시스템 수출 성사 (대한민국 정책브리핑)", u:"https://www.korea.kr/news/policyBriefingView.do?newsId=148706600"},
            {t:"세계와 공유한다: 전자정부 시리즈 (2) 전자통관시스템 유니패스 (코리아넷)", u:"https://www.korean-culture.org/koreanet/view.do?seq=6492"}]}
];
